(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var y2=function(a){a.S("cardstatechange",g.yN(a)&&g.zN(a)?1:0)},cwa=function(a){var b=g.Mh(a);
a=g.Th(a);return new g.vh(b.x,b.y,a.width,a.height)},dwa=function(a){return Math.pow(a,3)},ewa=function(a){return 3*a*a-2*a*a*a},z2=function(a,b){var c=g.Ao("use_default_events_client")?void 0:g.rr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Hk:g.Gs(a),kk:a};"UNDEFINED_CSN"==a?g.Us("visualElementShown",d,e):c?g.Wp("visualElementShown",d,c,e):g.sr("visualElementShown",d,e)})},A2=function(a,b){var c=g.Ao("use_default_events_client")?void 0:g.rr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Hk:g.Gs(a),kk:a,lG:e};"UNDEFINED_CSN"==a?g.Us("visualElementHidden",d,e):c?g.Wp("visualElementHidden",d,c,e):g.sr("visualElementHidden",d,e)})},D2=function(a){a=g.Ra(a);
delete B2[a];g.Rb(B2)&&C2&&C2.stop()},gwa=function(){C2||(C2=new g.G(function(){fwa()},20));
var a=C2;a.isActive()||a.start()},fwa=function(){var a=(0,g.E)();
g.Bb(B2,function(b){hwa(b,a)});
g.Rb(B2)||gwa()},E2=function(a,b,c,d){g.Kn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},hwa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;iwa(a,a.progress);1==a.progress?(a.o=0,D2(a),a.te(),a.Hn()):a.ub()&&a.mu()},iwa=function(a,b){g.Oa(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},jwa=function(a,b){g.Ne.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},F2=function(a,b,c,d,e){E2.call(this,b,c,d,e);
this.element=a},G2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
F2.call(this,a,b,c,d,e)},H2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},I2=function(a){return a.baseUrl||null},J2=function(a,b){return(0,g.ze)((0,g.Ic)(a,b,void 0),function(c){return!!c})},kwa=function(a,b,c){function d(Hb){var lb=Hb.hovercardButton;
if(!lb)return null;lb=lb.subscribeButtonRenderer;if(!lb)return null;var te=f(lb.unsubscribedButtonText),Zn=f(lb.subscribedButtonText);if(lb.subscribed){var $n=f(lb.subscriberCountWithUnsubscribeText);var ao=f(lb.subscriberCountText)}else $n=f(lb.subscriberCountText),ao=f(lb.subscriberCountWithSubscribeText);var Aj=null;return Hb.signinEndpoint&&(Aj=g.Lb(Hb,"signinEndpoint","webNavigationEndpointData","url"),!Aj)?null:te&&(Zn||Aj)?{subscribed:lb.subscribed,subscribeText:te,subscribeCount:$n,unsubscribeText:Zn,
unsubscribeCount:ao,enabled:lb.enabled,signinUrl:Aj,classic:Hb.useClassicSubscribeButton}:null}
function e(Hb){if(Hb){var lb=[],te=Hb.videoId;te&&lb.push("v="+te);(te=Hb.playlistId)&&lb.push("list="+te);(Hb=Hb.startTimeSeconds)&&lb.push("t="+Hb);return"/watch?"+lb.join("&")}}
function f(Hb){if(!Hb)return null;var lb=Hb.simpleText;return lb?lb:Hb.runs?(0,g.Ic)(Hb.runs,function(te){return te.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,B=!1,z=null,D=null,F=null,H=null,Z=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(B=g.Lb(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Lb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(Z=f(b.additionalFeesText)),(n=g.Lb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Lb(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,Nb="";if(b.metadata){var Gb=f(b.metadata);Gb&&(Nb=Gb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Nb,callToAction:f(b.callToAction),
az:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:z,subscribersText:D,isSubscribe:B,targetUrl:m,DH:n,Cc:{itct:K},cP:q,im:a?a:null,HH:b.isPlaceholder,impressionUrls:J2(b.impressionUrls||[],I2),uH:J2(b.hovercardShowUrls||[],I2),clickUrls:J2(l.loggingUrls||[],I2),visualElement:g.zs(b.trackingParams),productPrice:H,
additionalFeesText:Z}},K2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=J2(a.impressionUrls||[],I2);a.trackingParams&&(c.visualElement=g.zs(a.trackingParams));c.elements=J2(a.elements||[],function(d,e){return kwa(b,d,e)});
return c},L2=function(a){g.WN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.ty(a)||g.vy(a);this.R=!0;this.I=0;this.C=new g.is(this);g.C(this,this.C);this.C.L(this.player,g.dz("creatorendscreen"),this.hI);this.C.L(this.player,"crx_creatorendscreen",this.iI);this.C.L(this.player,"resize",this.YA);this.C.L(window,"focus",this.WN);this.load();var b=g.ue("STYLE");(g.ee("HEAD")[0]||document.body).appendChild(b);g.Ke(this,function(){g.ye(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},lwa=function(a){return a.player.getVideoData().fc?"current":a.N?"new":"current"},M2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},N2=function(a,b,c){c=void 0===c?!0:c;
g.AQ(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&mwa(a);c=[];d=new g.az(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.U({D:"div",J:"ytp-ce-shadow"}),g.IN(a.player,a.A.element,4),a.F=new g.qO(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=nwa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.IN(a.player,f.element,4);var h=new g.az(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);owa(a,f,e)}g.EN(a.player,c);
a.YA()}},mwa=function(a){var b=g.Ds(),c=g.Fs();
c&&b&&a.u.visualElement&&g.$s(c,b,a.u.visualElement)},nwa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.im||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:O2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:P2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.im||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:O2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:P2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.im||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],P:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Qn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:O2(b)}]};c=new g.U(c);var d=g.fe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Cc.itct}else e="endscreen",f=null;e=new g.zP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.im||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Qn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],P:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:O2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:pwa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.im||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Qn(b.title||"")},V:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:O2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.U(c)}b.HH&&g.I(c.element,"ytp-ce-placeholder");return c},O2=function(a){if(a.az)var b=a.az.thumbnails;
return pwa(b?b[b.length-1].url:null)},pwa=function(a){return a?{style:"background-image: url("+a+")"}:{}},owa=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.ma("mouseenter",(0,g.x)(a.dv,a,b,c));b.ma("mouseleave",(0,g.x)(a.Ov,a,b,c));a.player.O().o||b.ma("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ma("click",(0,g.x)(a.eC,a,c));b.ma("keypress",(0,g.x)(a.eC,a,c));b.ma("focus",(0,g.x)(function(l,m){this.dv(l,m)},a,b,c));
b.ma("blur",(0,g.x)(function(l,m){this.Ov(l,m)},a,b,c));
b.ma("touchstart",(0,g.x)(a.dv,a,b,c));var f=g.he("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.In(b.element,"ytp-ce-element-hover");g.In(b.element,"ytp-ce-force-expand")});
b.ma("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),Q2(this,m.id,!0)):(g.In(l.element,"ytp-ce-force-expand"),g.In(l.element,"ytp-ce-element-hover"),Q2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ma("blur",g.Sa(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.he("ytp-sb-subscribe",b.element));c(g.he("ytp-sb-unsubscribe",b.element));b.ma("focus",d);b.ma("blur",e)},P2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Zy(c)+b}else return"";return b},Q2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},R2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||M2(a))c&&c();else{b=qwa(a,b);var e=0,f=!1,h=new g.G(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Gr(b[a],d)}},S2=function(a,b,c){R2(a,b.clickUrls,c);
(a=g.Fs())&&b.DH&&g.at(a,b.visualElement)},qwa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(rwa(b[e],c));return d},rwa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},swa=function(a){return Array.isArray(a)&&a.length?a[0]:a},T2=function(a){return"string"===typeof a?a:""},U2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},twa=function(a){this.externalId=a},uwa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},V2=function(a){return a.value?a.value:null},W2=function(a){if(!a)return null;
var b=g.Dc(T2(a.value));b=g.zc(b);if(!b)return null;var c=U2(a.target,vwa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new uwa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},wwa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},zwa=function(a){if(!a)return null;
var b=U2(a.type,xwa),c=U2(a.trigger,ywa),d=swa(a.url);d=W2(d?d:null);a=swa(a.subscribeData);var e=a?a:null;e?(a=T2(e.external_user_id),e=T2(e.subscription_token),a=a&&e?new twa(a):null):a=null;return b?new wwa(b,c,d,a):null},X2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Awa=function(a,b){return g.cb(a.action,b,void 0)},Bwa=function(a,b){this.context=a;
this.o=b},Z2=function(a){return a.customMessage?Y2("div","iv-card-message",a.customMessage):""},$2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},a3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.p(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y2("li","",c.value));return{D:"ul",J:"iv-card-meta-info",K:b}},Y2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Qn(c);return{D:a,P:b,V:c}},Cwa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bp&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bp+");");c.dir=g.Qn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",W:b,P:c,K:d}},b3=function(a,b,c,d){if(d){b=g.p(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.Cc,c.ae.click,5)}},Dwa=function(a,b){this.merchant=a;
this.price=b},Ewa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Fwa=function(a,b){return b?b:Ewa(a)?"current":"new"},c3=function(a,b){g.A.call(this);
var c=this;this.element=a;this.context=b;this.sa=!1;this.ga=new Map;this.fa=new Map;this.context.H.addEventListener(g.dz("annotations_module"),function(d){(d=c.ga.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.fa.get(d))&&d.apply(c)})},d3=function(a,b,c,d,e,f,h){a.context.o.ma(b,"click",function(){a.jv(c,d,e,f||[],h||0)});
a.context.o.ma(b,"touchstart",function(){a.sa=!1});
a.context.o.ma(b,"touchmove",function(){a.sa=!0})},Gwa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},e3=function(a,b,c){return{iA:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
YD:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Xr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},h3=function(a,b,c){c3.call(this,b,c);
var d=this;this.H=a;this.eventId=null;this.Z=this.Ea=this.A=this.Hc=!1;this.aa=null;this.cards=[];this.va=this.I=this.Y=this.C=this.ea=this.o=null;this.N=[];this.G=this.zc=this.T=null;this.F=0;this.U=new g.G(g.Ka,c.B.eb?4E3:3E3);g.C(this,this.U);this.na=new g.G(g.Ka);g.C(this,this.na);this.R=new Bwa(c,function(e,f,h,l,m,n){d3(d,e,f,h,l,m,n)});
this.M=new g.U({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ra=new g.qO(this.M,330);g.C(this,this.ra);this.ya=g.he("iv-drawer-header-text",this.B);this.u=g.he("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ea&&f3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ea=d.A)&&g3(d)})},Hwa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){f3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){g3(a)});
var d=c.headerText;g.Ce(a.ya,d);a.I&&a.I.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.T=g.zs(c.trackingParams);a.G=g.zs(c.closeTrackingParams);a.zc=g.zs(c.iconTrackingParams)},Iwa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:i3(a,c,b,d),sponsored:!1,ae:e3(d,e,d.command),ah:d.trackingParams?g.zs(d.trackingParams):null,rf:e.trackingParams?g.zs(e.trackingParams):
null,zc:f&&f.trackingParams?g.zs(f.trackingParams):null,imageUrl:j3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,bp:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?W2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.command.urlEndpoint.url}):null};k3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:i3(a,c,b,d),sponsored:!1,ae:e3(d,e,d.endpoint),ah:d.trackingParams?g.zs(d.trackingParams):null,rf:e.trackingParams?g.zs(e.trackingParams):null,zc:f&&f.trackingParams?g.zs(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,
customMessage:d.customText?g.S(d.customText):null,cD:j3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:W2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};k3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:i3(a,c,b,d),sponsored:!1,ae:e3(d,e,d.action),ah:d.trackingParams?g.zs(d.trackingParams):null,rf:e.trackingParams?g.zs(e.trackingParams):null,zc:f&&f.trackingParams?g.zs(f.trackingParams):null,oo:j3(d.playlistThumbnail.thumbnails,
258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:W2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Gwa(d.action)})};k3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?
b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:i3(a,c,b,d),sponsored:!1,ae:e3(d,e,d.action),ah:d.trackingParams?g.zs(d.trackingParams):null,rf:e.trackingParams?g.zs(e.trackingParams):null,zc:f&&f.trackingParams?g.zs(f.trackingParams):null,oo:j3(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.S(d.lengthString):
null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:W2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Gwa(d.action)})};k3(a,c)}a.F++},j3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},i3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Kwa=function(a,b){var c=Jwa(a,b);
c&&(c===a.o&&(a.o=null),a.H.removeCueRange(c.card.id),g.ye(c.wt),g.kb(a.cards,c),a.ep(),l3(a))},f3=function(a,b,c){if(!a.A){a.ra.show();
a.ea=new g.G(function(){g.I(a.context.H.getRootNode(),g.hM.IV_DRAWER_OPEN)},0);
a.ea.start();a.aa=g.gp(a.u,"mousewheel",function(h){a.U.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.Fs();d&&a.T&&a.G&&z2(d,[a.T,a.G]);b={TRIGGER_TYPE:b};for(var e=g.p(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.JA||(f.JA=!0,Lwa(a.context.logger,f.card.ae.iA,b)),d&&z2(d,[f.card.ah]);y2(a.H);c&&(a.C=new g.G(function(){a.Y=a.I;a.va.focus()},330),a.C.start())}},g3=function(a){a.A&&(a.ra.hide(),g.hp(a.aa),a.aa=null,g.In(a.context.H.getRootNode(),g.hM.IV_DRAWER_OPEN),a.A=!1,y2(a.H),a.C&&a.C.stop(),a.C=new g.G(function(){a.Y&&(a.Y.focus(),a.Y=null)},330),a.C.start())},Nwa=function(a){g.Hn(a.xa(),
[g.hM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IN(a.H,a.B,5);Mwa(a);a.I=g.he("ytp-cards-button",a.H.getRootNode());a.va=g.he("iv-drawer-close-button",a.B);a.Hc=!0},Mwa=function(a){var b=g.he("iv-drawer-close-button",a.B);
a.context.o.ma(b,"click",a.SF,a);a.context.o.ma(a.u,"touchend",function(){a.U.start()});
a.context.o.ma(a.u,"scroll",a.jG,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.Gn(a.H.getRootNode(),"ytp-autohide")});
a.N.push(g.Ro("iv-button-shown",a.MH,a));a.N.push(g.Ro("iv-button-hidden",a.LH,a));a.N.push(g.Ro("iv-teaser-shown",a.RI,a));a.N.push(g.Ro("iv-teaser-hidden",a.NH,a));a.N.push(g.Ro("iv-teaser-clicked",a.QI,a))},k3=function(a,b){a.Hc||Nwa(a);
Kwa(a,b.id);var c=Owa(a,b);if(c){var d={card:b,wt:c.element,JA:!1},e=Pwa(a,d);g.sb(a.cards,e,0,d);c.ba(a.u,e);a.ep();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,l3(a),Qwa(a,d),f3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&Rwa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Rwa(a,d)}),l3(a))}},Owa=function(a,b){switch(b.type){case "simple":var c=a.R;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",V:b.displayDomain}:void 0;var e=Cwa(b);d={D:"div",W:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:b.url?V2(b.url)||"":""},K:[$2(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[Y2("h2",void 0,b.title),e]}]}]};d=new g.U(d);b3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.R,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],P:{href:V2(b.url)||"","data-ytid":b.channelId},K:[$2(b.cD),
{D:"div",J:"iv-card-content",K:[Z2(b),{D:"h2",J:"iv-card-primary-link",V:b.title},a3(b)]}]}]},d=new g.U(d),b3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.R,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:V2(b.url)||""},K:[$2(b.oo,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[Z2(b),Y2("h2","iv-card-primary-link",b.title),a3(b)]}]}]},d=new g.U(d),
b3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.R;var f=!g.gb(b.offers);d=["iv-card"];e="";var h=Cwa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",J:"iv-card-offer-price",V:h.price}),h.merchant&&f.push({D:"div",J:"iv-card-offer-merchant",V:h.merchant}),h={D:"div",K:f});f=b.url?V2(b.url)||"":"";d={D:"div",W:d,P:{tabindex:"0"},K:[{D:"a",W:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Patrocinado",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",V:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:f},K:[Y2("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.ue("span");g.Ce(e,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
d.Cb(e,"adInfo");b3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.R,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"EN DIRECTO AHORA"}:null,d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:V2(b.url)||""},K:[$2(b.oo,b.videoDuration?{D:"span",J:"iv-card-video-duration",V:b.videoDuration}:void 0),{D:"div",J:"iv-card-content",K:[Z2(b),Y2("h2","iv-card-primary-link",b.title),a3(b),d]}]}]},d=new g.U(d),b3(c,g.ge("iv-click-target",d.element),
b,b.url),d;default:return null}},Pwa=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},Swa=function(a){return a.o?"productListing"===a.o.card.type:(0,g.zi)(a.cards,function(b){return"productListing"===b.card.type})},l3=function(a){g.J(a.H.getRootNode(),"ytp-cards-shopping-active",Swa(a))},Rwa=function(a,b){if(!g.Gn(a.H.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.Fs(),d=a.o?a.o.card.zc:a.zc;
c&&d&&A2(c,[d]);a.o=b;l3(a)}if(c="none"!=a.xa().style.display)2===a.context.H.getPresentingPlayerType()?c=1===a.context.H.getAdState():(c=a.context.H.getPlayerState(),d=0===c&&0===a.context.H.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.xN(g.mN(a.H)))&&d.bv(!0,c));a.na.isActive()||((!a.A||!a.U.isActive()&&a.Z)&&Qwa(a,b),a.na.start(910+b.card.teaserDurationMs))}},Qwa=function(a,b){if(a.M.La()){var c=new E2([0,
a.u.scrollTop],[0,b.wt.offsetTop],600,ewa);a.context.A.ma(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ma(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.gM(a.M,!0),a.u.scrollTop=b.wt.offsetTop,g.gM(a.M,!1)},m3=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},Jwa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},n3=function(a,b,c){c3.call(this,a,b);
this.annotation=c;this.isActive=!1},Twa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},o3=function(a,b,c){n3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},Uwa=function(a,b){var c=void 0===c?0:c;
var d=cwa(b).width;g.Ih(b,d);c=new G2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,dwa);g.C(a,c);a.context.A.ma(c,"begin",function(){g.Uh(b,!0)});
c.play()},Xwa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
W:["iv-branding-context-name"],V:b.channel_name}),d=a.createElement({D:"div",W:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.zP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.H),a.o.ba(d));var f=a.createElement({D:"div",W:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",W:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Uh(h,!1);var l=a.createElement({D:"div",W:["branding-context-container-outer"]});l.appendChild(h);g.Ah(l,"right",b.image_width+"px");a.xa().appendChild(l);a.A=new g.G(function(){Vwa(a,h,l)},500);
g.C(a,a.A);a.context.o.ma(a.xa(),"mouseover",function(){Wwa(a,h,l,f,b.image_height)});
a.context.o.ma(a.xa(),"mouseout",function(){a.A.start()})}},Wwa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Th(b);a.o||(g.Rh(b,f.width),g.Rh(c,f.width));g.Ah(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ah(d,"right","1px");a.B=!0;g.Uh(b,!0);a.C=new g.G(function(){g.I(this.xa(),"iv-branding-active")},0,a);
a.C.start()}},Vwa=function(a,b,c){g.In(a.xa(),"iv-branding-active");
a.F=new g.G(function(){g.Uh(b,!1);a.o||g.Rh(c,0)},250);
a.F.start();a.B=!1},Ywa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},p3=function(a,b,c){n3.call(this,a,b,c);
var d=this;this.I=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.G=this.createElement({D:"div",W:["iv-promo-contents"]});this.C=new g.G(function(){d.o.setAttribute("aria-hidden","true");g.Uh(d.A,!1);g.Uh(d.u,!0)},700,this);
g.C(this,this.C)},Zwa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden","true");a.xa().setAttribute("aria-label","Promoci\u00f3n");a.xa().tabIndex=0;var e=a.annotation.yc(),f=b.image_url;if(f){var h=a.createElement({D:"div",W:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",P:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",J:"iv-promo-video-duration",V:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",V:b.playlist_length.toString()}),h.appendChild(f));e&&d3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.ad(f,V2(e)),a.o=f):a.o=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_1}]});
var m=a.createElement({D:"p",K:[{D:"span",J:"iv-promo-link",V:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",W:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",W:["iv-button","iv-promo-button"],K:[{D:"span",J:"iv-button-content",V:f}]});var q=a.createElement({D:"div",J:"iv-promo-button-container"});q.appendChild(f);e&&d3(a,a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&
d3(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",K:[{D:"span",V:b.text_line_1}]}),m=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",W:["yt-badge","iv-promo-badge-live"],V:"EN DIRECTO AHORA"})),g.I(a.o,"iv-click-target"),e&&d3(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);q&&a.G.appendChild(q);
c=a.createElement({D:"div",J:"iv-promo-actions"});a.u=a.createElement({D:"button",W:["iv-promo-expand","ytp-button"]});a.u.title="Expandir";a.context.o.ma(a.u,"click",function(r){q3(a,5E3,r)});
c.appendChild(a.u);g.Uh(a.u,!1);a.context.o.ma(a.xa(),"mouseover",a.cH,a);a.context.o.ma(a.xa(),"mouseout",a.bH,a);a.context.o.ma(a.xa(),"touchend",function(r){q3(a,5E3,r)});
a.A=a.createElement({D:"button",W:["iv-promo-close","ytp-button"]});a.A.title="Cerrar";a.context.o.ma(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.VG:a.UG,a);c.appendChild(a.A);g.Hn(a.xa(),d);h&&(a.xa().appendChild(h),n&&h.appendChild(n));a.xa().appendChild(a.G);a.xa().appendChild(c)},q3=function(a,b,c){c.stopPropagation();
$wa(a);axa(a,b);a.o.focus()},bxa=function(a){a.isCollapsed||a.I||a.B||(g.I(a.xa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},$wa=function(a){a.C.stop();
a.isCollapsed&&(g.Jn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Uh(a.u,!1),g.Uh(a.A,!0))},axa=function(a,b){a.B||(a.B=g.Zf(function(){r3(this);
bxa(this)},b,a))},r3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},cxa=function(a){this.H=a},Lwa=function(a,b,c){b&&(c?s3(a,b.map(function(d){return g.mn(d,c)})):s3(a,b))},s3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.p(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Gr(m,f);d&&(e++,0!==d&&a.H.sendVideoStatsEngageEvent(d,f))},t3=function(a){g.WN.call(this,a);
var b=this;this.M=!1;this.loadNumber=0;this.G={};this.logger=new cxa(this.player);this.C=new g.is(this);this.F=this.A=null;this.events=new g.is(this);this.I=this.o=null;this.N=[];g.C(this,this.C);this.C.L(this.player,"onVideoAreaChange",function(){b.S("onVideoAreaChange")});
this.C.L(this.player,"onHideControls",function(){b.S("onHideControls")});
this.C.L(this.player,"onShowControls",function(){b.S("onShowControls")});
this.C.L(this.player,"resize",function(d){b.S("resize",d)});
this.C.L(this.player,"presentingplayerstatechange",function(d){b.S("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.OI,this);this.subscribe("resize",this.rr,this);this.player.O().N.subscribe("vast_info_card_add",this.NC,this);g.C(this,this.events);this.R=this.createElement({D:"div",J:"video-custom-annotations"});this.u=new g.U({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.IN(this.player,this.u.element,4);this.u.hide();this.B=new g.U({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.B);a=this.createElement({D:"div",J:"video-annotations"});
a.appendChild(this.R);this.B.element.appendChild(a);dxa(this)&&this.load();var c=this.createElement({D:"style"});(g.ee("HEAD")[0]||document.body).appendChild(c);g.Ke(this,function(){g.ye(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},exa=function(a){a=a.createElement({D:"div",
W:["annotation","annotation-type-custom"]});g.Uh(a,!1);return a},dxa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.DE||b.N.get(a.videoId)||g.bC(a)||g.cC(a)?!0:!1},fxa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.gM(a.u,c);g.gM(a.B,c)},gxa=function(a,b,c){a.M=!0;
a.F=g.uq(b,c)},hxa=function(a,b){for(var c={},d=g.p(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(hxa(a,e))}return c},kxa=function(a){var b=a.player.getVideoData();
if(b.Ze){var c=a.player.O().N.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.oq(h)&&h.responseXML?h.responseXML:null)&&u3(a,h)}};
g.wp()&&(d.onFinish=ixa(a,d.onFinish));d.postParams={ic_only:"1"};jxa(d,c);a.M=!0;g.uq(b.Ze,d)}}},jxa=function(a,b){a.method="POST";
a.Gb=a.Gb||{};b.jp&&(a.Gb.ic_coll=b.jp);b.kp&&(a.Gb.ic_xml=b.kp);b.so&&(a.Gb.ic_track=b.so)},lxa=function(a){var b=new g.U({D:"div"});
g.Uh(b.element,!1);var c=new h3(a.player,b.element,v3(a));g.C(c,b);b.ba(a.u.element);c.co();return c},v3=function(a){if(!a.I){var b=new H2(a);
g.C(a,b);var c=new g.y1(a);g.C(a,c);a.I=new Ywa(b,c,a.player.O(),a.player.getVideoData(),a.logger,a.player,a.Ea)}return a.I},u3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Fs();if(e){var f=g.Ds();f&&g.Vs(g.Ao("use_default_events_client")?void 0:g.rr,e,f,[g.zs(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=hxa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=U2(h.type,mxa),r=U2(h.style,nxa),u=T2(h.data),w=0!==u.length?JSON.parse(u):{};var B=h.action;h=zwa;if(null==B)var z=null;else if(g.Na(B)){m=[];for(var D=g.p(B),F=D.next();!F.done;F=
D.next()){var H=h(F.value);H&&m.push(H)}z=m}else{var Z=h(B);z=Z?[Z]:[]}f=n&&q?new X2(n,q,r,z,w):null}else f=null}catch(te){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var K=exa(h),Nb=null;switch(m.type){case "branding":if(h.player.O().Ga)break;h.u.element.appendChild(K);Nb=new o3(K,v3(h),m);break;case "promotion":g.IN(h.player,K,4),Nb=new p3(K,v3(h),m)}Nb&&Nb.co();if(h=Nb)g.C(a,h),a.G[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.o||(a.o=lxa(a),g.C(a,a.o));if("card"===f.type){c=
a.o;var Gb=f&&f.data&&f.data.card_type;h=f.data;if(Gb)switch(m=h.tracking||{},m={iA:m.impression,click:m.click,close:m.close,YD:m.teaser_impression,Xr:m.teaser_click},K=h.tracking_params||{},Nb=null,Gb){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,ah:K.card?g.zs(K.card):null,rf:K.teaser?g.zs(K.teaser):null,zc:K.icon?
g.zs(K.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,cD:h.image_url,title:h.title,metaInfo:h.meta_info,url:W2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};k3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,ah:K.card?g.zs(K.card):null,
rf:K.teaser?g.zs(K.teaser):null,zc:K.icon?g.zs(K.icon):null,oo:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:W2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};k3(c,f);break;case "productListing":h.signin_url&&(Nb=W2({target:"current",value:h.signin_url}));Gb=[];for(var Hb=h.offers||[],lb=0;lb<Hb.length;lb++)Gb.push(new Dwa(g.id(Hb[lb].merchant),g.id(Hb[lb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,ah:K.card?g.zs(K.card):null,rf:K.teaser?g.zs(K.teaser):null,zc:K.icon?g.zs(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,bp:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:W2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),wU:Nb,vU:h.signin_title?h.signin_title:void 0,uU:h.signin_message?h.signin_message:void 0,offers:Gb};k3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,ah:K.card?g.zs(K.card):null,rf:K.teaser?g.zs(K.teaser):null,zc:K.icon?
g.zs(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,bp:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:W2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};k3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,ah:K.card?g.zs(K.card):null,rf:K.teaser?g.zs(K.teaser):null,zc:K.icon?g.zs(K.icon):null,oo:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:W2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},k3(c,f)}}else Hwa(a.o,f);c=!0}}c&&(y2(a.player),a.rr())},oxa=function(a,b){var c=!1;
a.o||(a.o=lxa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Iwa(a.o,e.cardRenderer),c=!0);c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Ce(c.ya,d),c.I&&c.I.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.T=b.trackingParams?g.zs(b.trackingParams):null,c.G=b.closeButton.infoCardIconRenderer.trackingParams?g.zs(b.closeButton.infoCardIconRenderer.trackingParams):null,c.zc=b.icon.infoCardIconRenderer.trackingParams?
g.zs(b.icon.infoCardIconRenderer.trackingParams):null,y2(a.player),a.rr())},pxa=function(a,b,c,d,e){if(!a.player.O().Ga){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new wwa("openUrl","click",new uwa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new X2(c,"branding","branding",f,d);d=exa(a);a.u.element.appendChild(d);f=new o3(d,v3(a),f);f.co();g.C(f,f);a.G[c]=f}},ixa=function(a,b){return function(c){for(var d=
[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ha()||(d.unshift(b),b=g.Sa.apply(window,d),a.N.push(g.up(b)))}},qxa=function(a){return"annotation-editor"===a||"live-dashboard"===a},B2={},C2=null;g.Ua(E2,g.Kn);g.k=E2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.ub())return!1;D2(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.mr();this.af("play");-1==this.o&&this.af("resume");this.o=1;var b=g.Ra(this);b in B2||(B2[b]=this);gwa();hwa(this,a);return!0};
g.k.stop=function(a){D2(this);this.o=0;a&&(this.progress=1);iwa(this,this.progress);this.af("stop");this.Hn()};
g.k.pause=function(){this.ub()&&(D2(this),this.o=-1,this.af("pause"))};
g.k.X=function(){0==this.o||this.stop(!1);this.af("destroy");E2.tc.X.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.mu=function(){this.af("animate")};
g.k.af=function(a){this.dispatchEvent(new jwa(a,this))};
g.Ua(jwa,g.Ne);g.Ua(F2,E2);F2.prototype.B=g.Ka;F2.prototype.mu=function(){this.B();F2.tc.mu.call(this)};
F2.prototype.Hn=function(){this.B();F2.tc.Hn.call(this)};
F2.prototype.mr=function(){this.B();F2.tc.mr.call(this)};
g.Ua(G2,F2);G2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(H2,g.A);H2.prototype.ma=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.gp(a,b,c);this.o.push(a);return a};
H2.prototype.Vu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.pp(a,b,c);this.o.push(a);return a};
H2.prototype.rb=function(a){g.hp(a);g.kb(this.o,a)};
H2.prototype.X=function(){g.hp(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.t(L2,g.WN);g.k=L2.prototype;g.k.load=function(){g.WN.prototype.load.call(this);if(!M2(this)){var a=g.aC(this.player.getVideoData());if(a)a=K2(a,lwa(this)),N2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",te:(0,g.x)(this.xL,this,a),tf:{v:a},withCredentials:!0};this.N&&(a.tf.ptype="embedded");var c=this.player.getVideoData().Ap;c&&(a.Gb={ad_tracking:c});if(b=g.$B(b))if(b=g.Dc(b),b=g.zc(b))this.B=g.uq(b,a)}}};
g.k.unload=function(){N2(this,null);this.B&&(this.B.abort(),this.B=null);g.WN.prototype.unload.call(this)};
g.k.fd=function(a,b){if(!M2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=K2(b,"new");N2(this,c);return!0}return null};
g.k.getOptions=function(){return M2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=K2(c,lwa(this)))}N2(this,c)};
g.k.YA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<rxa.length;f++){var h=Math.abs(b.width-rxa[f]);if(-1==e||d>=h)e=f,d=h}d=sxa[e];this.A&&g.Ah(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Sh(e.element,Math.round(h.width*a.width),f);g.Ih(e.element,m,n);g.Jn(e.element,txa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Jn(e.element,sxa);g.I(e.element,d);(e=g.fe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ah(e,"height",f+"px")}}}}};
g.k.hI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())R2(this,this.u.impressionUrls),(a=g.Fs())&&this.u.visualElement&&g.Ws(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");R2(this,c.impressionUrls);(b=g.Fs())&&g.Ws(b,c.visualElement);this.player.O().A&&this.player.oa("endscreenelementshown",a)}};
g.k.iI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.In(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.In(b,"ytp-ce-shown");this.player.O().A&&this.player.oa("endscreenelementhidden",a)}};
g.k.WN=function(a){var b=this;a.target===window&&(new g.G(function(){for(var c in b.o)g.Jn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.eC=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Gn(c,"ytp-ce-element");){g.Gn(c,"subscribe-label")&&S2(this,a);if(g.Gn(c,"ytp-ce-channel-subscribe"))return;c=g.Ae(c)}if(!c||g.Gn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Ov(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.cP?(S2(this,a),this.JD(),this.player.pauseVideo(),c=g.Dc(P2(this,a.targetUrl)),c=g.zc(c),g.xO(c,void 0,a.Cc)):(c=this.player.getVideoData().fc,
c=(0,g.x)(this.VO,this,c,P2(this,a.targetUrl),a.Cc),c=(0,g.x)(this.JD,this,c),S2(this,a,c))}}};
g.k.VO=function(a,b,c){var d=g.cq(b);a&&d&&(d.v||d.list)?g.DU(this.player.app,d.v,c,d.list,!1,void 0):g.wO(b,c)};
g.k.dv=function(a,b){g.Gn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.G(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),R2(this,b.uH),Q2(this,b.id,!0))};
g.k.Ov=function(a,b){g.In(a.element,"ytp-ce-element-hover");g.In(a.element,"ytp-ce-force-expand");Q2(this,b.id,!1)};
g.k.JD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var rxa=[346,426,470,506,570,640,853,1280,1920],sxa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),txa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var vwa={NQ:"current",jS:"new"};var xwa={CLOSE:"close",nS:"openUrl",sF:"subscribe"},ywa={DQ:"click",CLOSE:"close",vR:"hidden",YS:"rollOut",ZS:"rollOver",fT:"shown"};X2.prototype.yc=function(){var a=Awa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var nxa={lQ:"anchored",VE:"branding",CHANNEL:"channel",MQ:"cta",yR:"highlightText",NR:"label",PLAYLIST:"playlist",KS:"popup",lT:"speech",sF:"subscribe",xT:"title",VIDEO:"video",KT:"website"},mxa={VE:"branding",vQ:"card",SQ:"drawer",xR:"highlight",YR:"marker",PS:"promotion",TEXT:"text",NT:"widget"};g.t(c3,g.A);g.k=c3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.az(a,b,{id:c});a.namespace="annotations_module";d&&this.ga.set(a,d);e&&this.fa.set(a,e);g.EN(this.context.H,[a])};
g.k.co=function(){this.context.u.subscribe("resize",this.ep,this)};
g.k.xa=function(){return this.element};
g.k.jv=function(a,b,c,d,e,f){if(this.sa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ye(this.xa())};
g.k.ep=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V2(a);if(f){var h=Fwa(f,a.target),l=function(){a.o&&e.context.H.pauseVideo();var m=e.context.videoData.fc||!1,n=g.cq(f||"");m&&n&&(n.v||n.list)?g.DU(e.context.H.app,n.v,b,n.list,!1,void 0):g.xO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);s3(this.context.logger,c,l,d);Ewa(f)||(c=g.Fs(),d=b.itct,c&&d&&g.at(c,g.zs(d)))}};
g.k.X=function(){this.ga.clear();this.fa.clear();g.A.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.t(h3,c3);g.k=h3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.H.getRootNode())?(a=g.Th(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ep=function(){var a=this.isAvailable();g.Uh(this.xa(),a);g.J(this.context.H.getRootNode(),g.hM.IV_DRAWER_ENABLED,a);y2(this.H)};
g.k.destroy=function(){var a=g.xN(g.mN(this.H));a&&a.bv(!1,void 0);try{this.H.getRootNode().removeChild(this.B)}catch(b){}g.So(this.N);g.hp(this.aa);this.ea&&this.ea.dispose();this.C&&this.C.dispose();c3.prototype.destroy.call(this)};
g.k.SF=function(){if(this.A){s3(this.context.logger,m3(this).ae.close);var a=g.Fs();a&&this.G&&g.at(a,this.G);g3(this)}};
g.k.jG=function(){g.J(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.MH=function(){var a=g.Fs(),b=m3(this);b=b?b.zc:this.zc;a&&b&&z2(a,[b])};
g.k.LH=function(){var a=g.Fs(),b=m3(this);b=b?b.zc:this.zc;a&&b&&A2(a,[b])};
g.k.RI=function(){var a=m3(this);s3(this.context.logger,a.ae.YD);var b=g.Fs();b&&a&&z2(b,[a.rf,a.zc])};
g.k.NH=function(){var a=g.Fs(),b=m3(this);a&&b&&A2(a,[b.rf])};
g.k.QI=function(a){var b=m3(this),c=g.Fs();this.o?a?(a=this.context.logger,s3(a,b.ae.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.rf&&g.at(c,b.rf)):(a=this.context.logger,s3(a,b.ae.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.zc&&g.at(c,b.zc)):(a=this.context.logger,s3(a,b.ae.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&this.zc&&g.at(c,this.zc))};g.t(n3,c3);n3.prototype.co=function(){c3.prototype.co.call(this);Twa(this)};
n3.prototype.show=function(){c3.prototype.show.call(this);var a=g.Fs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&z2(a,[g.zs(b.itct)])};
n3.prototype.hide=function(){c3.prototype.hide.call(this);var a=g.Fs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&A2(a,[g.zs(b.itct)])};g.t(o3,n3);
o3.prototype.show=function(){if(!this.isActive){n3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",W:["branding-img","iv-click-target"],P:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Uh(this.u,!1);var b=this.createElement({D:"div",W:["branding-img-container"]});b.appendChild(this.u);this.xa().appendChild(b);(b=this.annotation.yc())&&d3(this,this.u,b,this.annotation.id,
a.session_data);Xwa(this,a);this.G=!0}g.Uh(this.xa(),!0);this.isActive=!0;this.u&&Uwa(this,this.u)}};
o3.prototype.hide=function(){this.isActive&&(n3.prototype.hide.call(this),g.Uh(this.xa(),!1),this.isActive=!1)};
o3.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);n3.prototype.destroy.call(this)};g.t(p3,n3);g.k=p3.prototype;g.k.show=function(){this.isActive||(n3.prototype.show.call(this),this.M||(Zwa(this),this.M=!0),g.Uh(this.xa(),!0),g.Zf(function(){g.In(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,r3(this),$wa(this),axa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden","true"))};
g.k.jv=function(a,b,c,d,e,f){return this.isCollapsed?!1:n3.prototype.jv.call(this,a,b,c,d,e,f)};
g.k.cH=function(a){this.I=!0;q3(this,500,a)};
g.k.bH=function(){this.I=!1;bxa(this)};
g.k.UG=function(a){a.stopPropagation();this.hide()};
g.k.VG=function(a){a.stopPropagation();r3(this);this.isCollapsed=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();n3.prototype.destroy.call(this)};g.t(t3,g.WN);g.k=t3.prototype;g.k.fd=function(a,b){if(!qxa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.x1(b);c&&u3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Kwa(this.o,b),y2(this.player)),!0}return null};
g.k.getOptions=function(){return qxa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.rr=function(){if(this.B){var a=g.rN(this.player).getVideoContentRect(!0);g.Sh(this.B.element,a.width,a.height);g.Ih(this.B.element,a.left,a.top)}if(this.o){var b=this.player.Wk();a=this.o;b=b.width;g.J(a.B,"iv-drawer-small",426>=b);g.J(a.B,"iv-drawer-big",1280<=b)}};
g.k.OI=function(a){fxa(this,a.state);g.T(a.state,2)&&(this.qn()&&this.SA()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.bv(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.F=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.oq(h)&&h.responseXML?h.responseXML:null)&&(u3(b,h),g.I(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.WN.prototype.load.call(this);fxa(this,g.rM(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.wp()&&(a=ixa(this,a));var e={format:"XML",te:a,onError:function(){b.F=null},
tf:{}};c.isPharma&&(e.tf.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.O().N.get(d);f&&jxa(e,f);f=f&&(f.kp||f.jp);if(!c.Wo||f)c.Ze?gxa(this,c.Ze,e):(this.A=function(){b.Na(e)},this.player.addEventListener("videodatachange",this.A));
g.IN(this.player,this.B.element,4);this.rr();(f=g.bC(c))&&oxa(this,f);(f=g.cC(c))&&f.featuredChannel&&pxa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Na=function(a){var b=this.player.getVideoData();b.Ze&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),gxa(this,b.Ze,a))};
g.k.unload=function(){g.AQ(this.player.app,"annotations_module",void 0);for(var a=g.p(Object.keys(this.G)),b=a.next();!b.done;b=a.next())this.G[b.value].destroy();this.I=null;this.o&&(this.o.destroy(),this.o=null,y2(this.player));this.M=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.WN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.NC=function(a){a===this.player.getVideoData().videoId&&(this.loaded?kxa(this):this.load())};
g.k.qn=function(){return!!this.o&&this.o.isAvailable()};
g.k.SA=function(){this.qn();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.qn();this.o&&(a?c?f3(this.o,c,b):f3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):g3(this.o))};
g.k.bv=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.X=function(){this.player.O().N.unsubscribe("vast_info_card_add",this.NC,this);g.In(this.player.getRootNode(),g.hM.IV_DRAWER_OPEN);for(var a=this.N,b=0,c=a.length;b<c;b++)g.xp(a[b]);this.N.length=0;g.WN.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.gO.annotations_module=t3;g.gO.creatorendscreen=L2;})(_yt_player);
