(function(g){var window=this;var Rza=function(a,b){return g.Ob(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.jn(a.A,b,c)},Sza=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.io.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.ho(e)&&c.push(d)},a);
return c},Tza=function(a,b){var c=Sza(a,b);
(0,g.y)(c,function(d){g.io.prototype.remove.call(this,d)},a)},Uza=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},Vza=function(a,b){g.fb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},Wza=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},d6=function(){},Xza=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Yza=function(a){if(a.Wd&&"function"==typeof a.Wd)return a.Wd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},Zza=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.cf&&"function"==typeof a.cf)var c=a.cf();else if(a.Wd&&"function"==typeof a.Wd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=Yza(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},$za=function(a,b,c,d){var e=new g.Xm(null,void 0);
a&&g.Ym(e,a);b&&g.Zm(e,b);c&&g.$m(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Po[a]=!0;
var c=g.No();c&&c.publish.apply(c,arguments);g.Po[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Um;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",aAa(this,a.capabilities||""),bAa(this,a.experiments||""))},aAa=function(a,b){a.capabilities.clear();
(0,g.ze)(b.split(","),g.Sa(Rza,cAa)).forEach(function(c){a.capabilities.add(c)})},bAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},dAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},eAa=function(a){return new g6(a)},fAa=function(a){return Array.isArray(a)?(0,g.Ic)(a,eAa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Ic)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},gAa=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.cb(a,function(c){return h6(c,b)})},hAa=function(){var a=(0,g.ct)();
a&&Tza(a,a.o.Th(!0))},n6=function(){var a=g.ft("yt-remote-connected-devices")||[];
g.xb(a);return a},iAa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},jAa=function(a){g.et("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.ft("yt-remote-device-id");a||(a=k6(),g.et("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.fb(a,b);g.ht()&&g.zb(a,b);a=iAa(a);if(g.gb(a))try{g.Bq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Cq("remote_sid",a.join(","),-1)}catch(c){}},kAa=function(){return g.ft("yt-remote-session-browser-channel")},lAa=function(){return g.ft("yt-remote-local-screens")||[]},mAa=function(){g.et("yt-remote-lounge-token-expiration",!0,86400)},nAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(lAa(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.zi)(c,function(d){return!g.fb(b,d)})&&mAa();
g.et("yt-remote-local-screens",a,31536E3)},oAa=function(a,b){g.et("yt-remote-session-browser-channel",a);
g.et("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.fb(c,d)||c.push(d);jAa(c);q6()},r6=function(a){a||(g.gt("yt-remote-session-screen-id"),g.gt("yt-remote-session-video-id"));
q6();a=n6();g.kb(a,p6());jAa(a)},pAa=function(){if(!s6){var a=g.oo();
a&&(s6=new g.bo(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},qAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},rAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?sAa(a.shift(),function(){t6(a)}):u6()},tAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},sAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=rAa();
a&&a(!1,"No cast extension found")},vAa=function(){if(uAa){var a=2,b=rAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;sAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},wAa=function(){vAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Ld=b;this.C=(0,g.x)(this.PG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Ld=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.Zf(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Ld);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Xza(a)},z6=function(){},A6=function(){},xAa=function(){},zAa=function(a){return(a=yAa(a))?new ActiveXObject(a):new XMLHttpRequest},yAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.y1(this);this.u=new g.Yf;this.u.setInterval(250)},BAa=function(a,b,c){a.Sl=1;
a.Wh=a6(b.clone());a.hk=c;a.F=!0;AAa(a,null)},C6=function(a,b,c,d,e){a.Sl=1;
a.Wh=a6(b.clone());a.hk=null;a.F=c;e&&(a.ID=!1);AAa(a,d)},AAa=function(a,b){a.Ml=(0,g.E)();
D6(a);a.Qi=a.Wh.clone();b6(a.Qi,"t",a.G);a.yo=0;a.dd=a.o.Jt(a.o.jo()?b:null);0<a.ru&&(a.Cr=new w6((0,g.x)(a.HE,a,a.dd),a.ru));a.B.ma(a.dd,"readystatechange",a.vO);var c=a.yj?g.Ub(a.yj):{};a.hk?(a.ws="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.dd.send(a.Qi,a.ws,a.hk,c)):(a.ws="GET",a.ID&&!g.oe&&(c.Connection="close"),a.dd.send(a.Qi,a.ws,null,c));a.o.Sf(1)},EAa=function(a,b,c){for(var d=!0;!a.fj&&a.yo<c.length;){var e=CAa(a,c);
if(e==E6){4==b&&(a.li=4,F6(15),d=!1);break}else if(e==DAa){a.li=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.li=1,F6(17),d=!1);a.ag=a.ag&&d;d||(H6(a),I6(a))},CAa=function(a,b){var c=a.yo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return DAa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.yo=d+c;return e},GAa=function(a,b){a.Ml=(0,g.E)();
D6(a);var c=b?window.location.hostname:"";a.Qi=a.Wh.clone();$5(a.Qi,"DOMAIN",c);$5(a.Qi,"t",a.G);try{a.gg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.li=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in FAa)h=J6[l]=FAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Zc(g.ec("b/12014412"),d+"</body></html>");a.gg.open();a.gg.write(g.Vc(c));a.gg.close();a.gg.parentWindow.m=(0,g.x)(a.JN,a);a.gg.parentWindow.d=(0,g.x)(a.MC,a,!0);a.gg.parentWindow.rpcClose=(0,g.x)(a.MC,a,!1);c=a.gg.createElement("DIV");a.gg.parentWindow.document.body.appendChild(c);d=g.Dc(a.Qi.toString());d=g.gd(g.zc(d));d=g.Zc(g.ec("b/12014412"),'<iframe src="'+d+'"></iframe>');g.$c(c,d);a.o.Sf(1)},D6=function(a){a.ox=(0,g.E)()+a.C;
HAa(a,a.C)},HAa=function(a,b){if(null!=a.Zl)throw Error("WatchDog timer not null");
a.Zl=K6((0,g.x)(a.TN,a),b)},L6=function(a){a.Zl&&(g.v.clearTimeout(a.Zl),a.Zl=null)},I6=function(a){a.o.Sz()||a.fj||a.o.Zp(a)},H6=function(a){L6(a);
g.Le(a.Cr);a.Cr=null;a.u.stop();g.wua(a.B);if(a.dd){var b=a.dd;a.dd=null;b.abort();b.dispose()}a.gg&&(a.gg=null)},G6=function(a,b){try{a.o.DC(a,b),a.o.Sf(4)}catch(c){}},JAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;IAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){JAa(a,b,c,d,f)},f)})}},IAa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Wza(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},KAa=function(a){this.o=a;
this.u=new z6},LAa=function(a){var b=N6(a.o,a.om,"/mail/images/cleardot.gif");
a6(b);JAa(b.toString(),5E3,(0,g.x)(a.NF,a),3,2E3);a.Sf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.ze=new B6(a,void 0,void 0,void 0),a.ze.yj=a.pu,b=a.o,b=N6(b,b.jo()?a.Tm:null,a.qu),F6(5),!g.me||g.Qd(10))b6(b,"TYPE","xmlhttp"),C6(a.ze,b,!1,a.Tm,!1);else{b6(b,"TYPE","html");var c=a.ze;a=!!a.Tm;c.Sl=3;c.Wh=a6(b.clone());GAa(c,a)}},Q6=function(a){g.nf.call(this);
this.headers=new g.Um;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.fa="";this.R=this.Z=!1},MAa=function(a){return g.me&&g.Pd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},NAa=function(a){return"content-type"==a.toLowerCase()},PAa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;OAa(a);R6(a)},OAa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},RAa=function(a){if(a.A&&"undefined"!=typeof g.D1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.Zf(a.zC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.qd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!QAa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";OAa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){SAa(a);
var c=a.o,d=a.U[0]?g.Ka:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},SAa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},TAa=function(a,b){this.o=a;
this.map=b;this.context=null},UAa=function(a){g.Ne.call(this,"statevent",a)},VAa=function(a,b,c,d){g.Ne.call(this,"timingevent",a);
this.size=b;this.Yn=d},WAa=function(a){g.Ne.call(this,"serverreachability",a)},ZAa=function(a){XAa(a);
if(3==a.o){var b=a.Cn++,c=a.Ip.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Sl=2;b.Wh=a6(c.clone());Wza(new Image,b.Wh.toString());b.Ml=(0,g.E)();D6(b)}YAa(a)},$Aa=function(a){a.nG(1,0);
a.Ip=N6(a,null,a.ou);X6(a)},XAa=function(a){a.Zh&&(a.Zh.abort(),a.Zh=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Yg&&(g.v.clearTimeout(a.Yg),a.Yg=null);Y6(a);a.le&&(a.le.cancel(),a.le=null);a.di&&(g.v.clearTimeout(a.di),a.di=null)},aBa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new TAa(a.uK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.le||a.di||(a.di=K6((0,g.x)(a.LC,a),0),a.Qk=0)},cBa=function(a,b){if(1==a.o){if(!b){a.Cn=Math.floor(1E5*Math.random());
var c=a.Cn++,d=new B6(a,"",c,void 0);d.yj=a.Xk;var e=Z6(a),f=a.Ip.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);BAa(d,f,e);a.le=d;a.o=2}}else 3==a.o&&(b?bBa(a,b):0==a.u.length||a.le||bBa(a))},bBa=function(a,b){if(b)if(6<a.gj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Cn-1;var d=Z6(a)}else c=b.I,d=b.hk;else c=a.Cn++,d=Z6(a);var e=a.Ip.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.ol);W6(a,e);c=new B6(a,a.A,c,a.Qk+1);c.yj=a.Xk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.le=c;BAa(c,e,d)},W6=function(a,b){if(a.Id){var c=a.Id.qz();
c&&g.Bb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.gj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.gj?e:f-d;try{g.Bb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},dBa=function(a){a.Ec||a.Yg||(a.G=1,a.Yg=K6((0,g.x)(a.KC,a),0),a.Ck=0)},$6=function(a){if(a.Ec||a.Yg||3<=a.Ck)return!1;
a.G++;a.Yg=K6((0,g.x)(a.KC,a),eBa(a,a.Ck));a.Ck++;return!0},O6=function(a,b,c){a.ts=c;
a.sg=b.ph;a.F||$Aa(a)},Y6=function(a){null!=a.kj&&(g.v.clearTimeout(a.kj),a.kj=null)},eBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Id&&(c=null);var d=(0,g.x)(a.eP,a);c||(c=new g.Xm("//www.google.com/images/cleardot.gif"),a6(c));IAa(c.toString(),1E4,d)}else F6(2);fBa(a,b)},fBa=function(a,b){a.o=0;
a.Id&&a.Id.Fy(b);YAa(a);XAa(a)},YAa=function(a){a.o=0;
a.sg=-1;if(a.Id)if(0==a.B.length&&0==a.u.length)a.Id.xt();else{g.pb(a.B);var b=g.pb(a.u);a.B.length=0;a.u.length=0;a.Id.xt(b)}},N6=function(a,b,c){var d=g.en(c);
if(""!=d.o)b&&g.Zm(d,b+"."+d.o),g.$m(d,d.B);else{var e=window.location;d=$za(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Im&&g.Bb(a.Im,function(f,h){$5(d,h,f)});
$5(d,"VER",a.gj);W6(a,d);return d},K6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new UAa(b7,a))},gBa=function(){},hBa=function(){this.o=[];
this.u=[]},iBa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.A.call(this);
this.o=new g.G(this.CN,0,this);g.C(this,this.o);this.Ld=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.N=a;this.F=b;this.A=new g.Yn;this.u=new c7(this.JO,this);this.o=null;this.Rc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.U=c;this.R=d},jBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ts,sessionId:a.o.A,arrayId:a.o.ol}},kBa=function(a,b){a.I=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.o&&cBa(a.o),ZAa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},e7=function(a){if(a.o){var b=a.R(),c=a.o.Xk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.Xk=c}},lBa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.qd(4,a))||"";b&&(this.port=":"+b);this.domain=g.rd(a)||"";a=g.Oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Bd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.B,d,!0),onError:g.Sa(a.A,e),Re:g.Sa(a.C,e)};c&&(a.Gb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uq(b,a)},pBa=function(){var a=mBa;
nBa();j7.push(a);oBa(j7)},k7=function(a,b){nBa();
var c=j7,d=qBa(a,String(b));g.gb(c)?rBa(d):(oBa(c),(0,g.y)(c,function(e){e(d)}))},nBa=function(){j7||(j7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},rBa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},oBa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},qBa=function(a,b){var c=((0,g.E)()-sBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.O.call(this);
this.F=a;this.screens=[]},tBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},uBa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ze)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=tBa(a,b[d])||c;return c},vBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.ze)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.O.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},wBa=function(a){if(a.screens.length){var b=(0,g.Ic)(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.aH,a),(0,g.x)(a.ZG,a))}},q7=function(a){var b=fAa(lAa());
b=(0,g.ze)(b,function(c){return!c.uuid});
return uBa(a,b)},s7=function(a,b){nAa((0,g.Ic)(a.screens,dAa));
b&&mAa()},u7=function(a,b){g.O.call(this);
this.F=b;var c=g.ft("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.Ok(this.o))},xBa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Ok(a.o)),a.o=b,a.S("screenChange"));yBa(a)},w7=function(a){isNaN(a.A)||g.Mo(a.A);
a.A=g.Ko((0,g.x)(a.mw,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},zBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},yBa=function(a){a=g.Kb(g.Cb(a.o,function(b){return b}));
g.xb(a);a.length?g.et("yt-remote-online-screen-ids",a.join(","),60):g.gt("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};ABa(this)},CBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Le();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);xBa(a.o,l,function(m){e(m?l:null)})}else c?BBa(a,c,(0,g.x)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));xBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},DBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},BBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Gb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},EBa=function(a){a.screens=a.u.Le();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},ABa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.hH,a));EBa(a);a.A=fAa(g.ft("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.x)(a.Le,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.et("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,dAa)));z7(a);a.B[b.uuid]=b.id;g.et("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.ft("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.O.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.LP,this);this.B=(0,g.x)(this.bO,this);this.A=g.Ko((0,g.x)(function(){FBa(this,null)},this),12E4)},GBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ok(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Ok(b))},FBa=function(a,b){g.Mo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.sr,a),d=(0,g.x)(a.Qe,a);a.Lz(b,c,d,5)}}else a.Qe(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.OP,this);this.u=g.Ka},HBa=function(a){a.u=a.M.OE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.sr(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Qe(b)},a))},IBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}pAa()&&(b.env_useStageMdx=1);return g.zd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.Ko((0,g.x)(this.pl,this,null),150)},F7=function(a,b,c,d){g.O.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.RM,this)},JBa=function(a,b){return b?g.cb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},mBa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Le(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.IC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.pl(null)):a.S("yt-remote-cast2-session-change",null))},KBa=function(a){var b=a.u.NE(),c=a.o&&a.o.o;
a=(0,g.Ic)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=JBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},QBa=function(a,b,c,d,e,f,h){LBa()?MBa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?NBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?NBa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.gt("yt-remote-cast-available"),g.gt("yt-remote-cast-receiver"),OBa(),c(!1))},d?g.Wo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?wAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(vAa(),t6(PBa.map(tAa))))):J7("Cannot initialize because not running Chrome")},OBa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);RBa(!1);g.So(O7);O7.length=0},P7=function(){return!!g.ft("yt-remote-cast-installed")},SBa=function(){var a=g.ft("yt-remote-cast-receiver");
return a?a.friendlyName:null},TBa=function(){J7("clearCurrentReceiver");
g.gt("yt-remote-cast-receiver")},UBa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.Ro("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},LBa=function(){var a=0<=g.Oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Xw||a},VBa=function(a,b){N7().init(a,b)},MBa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.et("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.gt("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},NBa=function(a,b){M7(!0);
K7(!1);VBa(a,function(c){c?(RBa(!0),g.To("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.gt("yt-remote-cast-available"),g.gt("yt-remote-cast-receiver"),OBa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.et("yt-remote-cast-installed",a)},Q7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},RBa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.tg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.tg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.ub()?((0,g.E)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.E)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Vb(a.o);b.hasPrevious=a.tg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.O.call(this);
this.o=0;this.B=a;this.F=[];this.C=new hBa;this.A=this.u=null;this.M=(0,g.x)(this.bL,this);this.G=(0,g.x)(this.Gn,this);this.I=(0,g.x)(this.aL,this);this.N=(0,g.x)(this.jL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.sx,this),WBa(this))):c=3;0!=c&&(b?this.sx(c):g.Ko((0,g.x)(function(){this.sx(c)},this),0));
var d=UBa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.B.getPlayerContextData())},WBa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Sa(this.OM,b),this))},a)},XBa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){XBa(a);
a.B.setPlayerContextData(Z7(b));WBa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Gn(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Gn(a.A.media[0]))},YBa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.Y=a;this.U.push(g.gp(window,"beforeunload",(0,g.x)(this.TG,this)));this.u=[];this.ib=new T7;this.T=b.id;this.o=ZBa(this,c);this.o.subscribe("handlerOpened",this.fL,this);this.o.subscribe("handlerClosed",this.cL,this);this.o.subscribe("handlerError",this.dL,this);this.o.subscribe("handlerMessage",this.eL,this);lBa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.ht()&&g.et("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},ZBa=function(a,b){return new d7(h7(a.Y,"/bc"),b,!1,function(){return a.KE()})},j8=function(a,b){a.S("proxyStateChange",b)},$Ba=function(a){a.C=g.Ko((0,g.x)(function(){i8("Connecting timeout");
this.Lk(1)},a),2E4)},k8=function(a){g.Mo(a.C);
a.C=NaN},l8=function(a){g.Mo(a.N);
a.N=NaN},aCa=function(a){m8(a);
a.M=g.Ko((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Mo(a.M);
a.M=NaN},cCa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.Jz()&&a.ib.reset(),j8(a,1),n8(a,"getNowPlaying"),bCa(a)):a.Lk(1)},dCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Rb(b.params)?a.ib.o=null:a.ib.o=b.params,a.S("remotePlayerChange"))},eCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Y7(a.ib,c,d);a.S("remoteQueueChange")},gCa=function(a,b){b.params=b.params||{};
eCa(a,b);fCa(a,b);a.S("autoplayDismissed")},fCa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?aCa(a):m8(a);a.S("remotePlayerChange")},hCa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.ib,isNaN(c)?0:c);a.S("remotePlayerChange")}},iCa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.S("remotePlayerChange")},jCa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},kCa=function(a,b){var c="true"==b.params.hasNext;
a.ib.tg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.S("previousNextChange")},bCa=function(a){g.Mo(a.I);
a.I=g.Ko((0,g.x)(a.Lk,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Ok(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Kd=a;this.o=[];this.o.push(this.Kd.$_s("screenChange",(0,g.x)(this.JP,this)));this.o.push(this.Kd.$_s("onlineScreenChange",(0,g.x)(this.rM,this)))},pCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;hAa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),pAa()&&(p8.o="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));lCa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);QBa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Ok(b)),u8.push(g.Ro("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.Ro("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.Ro("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.Ro("yt-remote-cast2-session-change",mCa)),u8.push(g.Ro("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),TBa())})),a=x8(),b.isAuto&&(a.id+="#dial"),g.Ao("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),t8(" -- with channel params: "+
g.Ok(a)),nCa(a),c.start(),s8()||oCa())},rCa=function(){var a=qCa();
P7()&&g.ft("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},qCa=function(){var a=r8().Kd.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return gAa(a)},A8=function(){var a=sCa();
!a&&P7()&&SBa()&&(a={key:"cast-selector-receiver",name:SBa()});return a},sCa=function(){var a=qCa(),b=y8();
b||(b=w8());return g.cb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Le();return m6(b,a)},mCa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},tCa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},uCa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||tCa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&((0,g.y)(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.ht();
if(!a)return null;var b=r8();if(!b)return null;b=b.Le();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{tCa(a.id);var c=new h8(p8,a,x8());c.connect(b,uCa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},oCa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),TBa(),t8("Skipping connecting because no session screen found."))},lCa=function(){var a=x8();
if(g.Rb(a)){a=p6();var b=g.ft("yt-remote-session-name")||"",c=g.ft("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},nCa=function(a){a?(g.et("yt-remote-session-app",a.app),g.et("yt-remote-session-name",a.name)):(g.gt("yt-remote-session-app"),g.gt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.ab=c;this.events=new g.is(this);this.M=this.events.L(this.H,"onVolumeChange",this.kC);this.B=!1;this.suggestion=null;this.C=new g.fG(64);this.o=new g.G(this.SD,500,this);this.u=new g.G(this.TD,1E3,this);this.G=new v6(this.oP,0,this);this.A={};this.I=new g.G(this.wE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ka;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.SL);this.events.L(b,"captionschanged",this.ZK);this.events.L(b,"captionssettingschanged",
this.WD);this.events.L(b,"videoplayerreset",this.tr);this.events.L(b,"mdxautoplaycancel",function(){d.ab.Zy()});
a=this.ab;a.ha();a.subscribe("proxyStateChange",this.CC,this);a.subscribe("remotePlayerChange",this.Mn,this);a.subscribe("remoteQueueChange",this.tr,this);a.subscribe("previousNextChange",this.yC,this);a.subscribe("nowAutoplaying",this.uC,this);a.subscribe("autoplayDismissed",this.UB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.WD();this.tr();this.Mn()},vCa=function(a){a.Xb(0);
a.o.stop();a.Pc(new g.fG(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Xb(c,b));a.ab.LE(a.H.getVideoData(1).videoId,c);a.A=b8(a.ab).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.ab.playVideo(c.videoId,b,d,e,c.playerParams,c.hf,Uza(c));a.Pc(new g.fG(1))},wCa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{jA:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.ab).videoId===a.H.getVideoData(1).videoId},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Pronto dejar\u00e1 de ser posible establecer una conexi\u00f3n web con una TV mediante un c\u00f3digo"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"M\u00e1s informaci\u00f3n"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"Aceptar"}]}]}]});
this.o=new g.qO(this,250);this.learnMoreButton=this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},N8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"No has iniciado sesi\u00f3n"},{D:"div",J:"ytp-mdx-popup-description",V:"Los v\u00eddeos que veas podr\u00edan aparecer en el historial de reproducciones de la TV e influir en las recomendaciones. Puedes evitarlo si cancelas e inicias sesi\u00f3n en YouTube desde tu ordenador."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],
V:"Cancelar"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"Confirmar"}]}]}]});this.o=new g.qO(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},O8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.tM()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.qO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);xCa(this,g.rM(a))},xCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.UL("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.ub()||g.T(b,4)?g.UL("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.UL("Conectado a $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.LR.call(this,"Reproducir en",0,a,b);
this.H=a;this.Pi={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.WN.call(this,a);
this.Nf={key:k6(),name:"Este ordenador"};this.lg=null;this.subscriptions=[];this.Xv=this.ab=null;this.Pi=[this.Nf];this.bi=this.Nf;this.Tb=new g.fG(64);this.CA=0;this.kd=-1;this.rl=null;this.Nn=this.Bq=!1;this.gk=this.Jl=null;if(!g.Ey(this.player.O())){a=this.player;var b=g.iN(a);b&&(b=b.vj())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.IN(a,b.element,4);this.Jl=new N8;g.C(this,this.Jl);g.IN(a,this.Jl.element,4);g.Q(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.rl=new M8,g.C(this,this.rl),g.IN(a,this.rl.element,4));this.Nn=!!w8();this.Bq=!!g.ft("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.gk&&(a.player.removeEventListener("presentingplayerstatechange",a.gk),a.gk=null)},yCa=function(a,b,c){a.Tb=c;
a.player.S("presentingplayerstatechange",new g.oG(c,b))},zCa=function(a,b,c){var d=!1;
1===b?d=!a.Nn:2===b&&(d=!a.Bq);d&&g.qG(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.bi.key)if(b.key===a.Nf.key)B8();
else{if(a.rl&&!a.Bq&&b!==a.Nf&&"cast-selector-receiver"!==b.key&&g.Ny(a.player.O()))ACa(a);else{var c;(c=!g.Q(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Nn||!a.Jl);(c?0:g.Ny(a.player.O())||g.Ry(a.player.O()))&&BCa(a)}a.bi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ba(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.hf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Uza(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Ok(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Le(),(c=m6(c,b.key))&&C8(c,1))}},BCa=function(a){g.rM(a.player).ub()?a.player.pauseVideo():(a.gk=function(b){zCa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.Jl&&a.Jl.Yb();z8()||(G8=!0)},ACa=function(a){g.rM(a.player).ub()?a.player.pauseVideo():(a.gk=function(b){zCa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.rl&&a.rl.Yb();z8()||(G8=!0)},FAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},CCa={},cAa={qQ:"atp",iT:"ska",SS:"que",hS:"mus",hT:"sus",pR:"dsp",aT:"seq"},s6,o6="",uAa=qAa("loadCastFramework")||qAa("loadCastApplicationFramework"),PBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(v6,g.A);g.k=v6.prototype;g.k.OG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Ld:this.Ka=g.Zf(this.C,this.Ld)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.tc.X.call(this)};
g.k.PG=function(){this.A?(this.Ka=g.Zf(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.A);g.k=w6.prototype;g.k.QA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},yAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Ua(xAa,A6);T8=new xAa;g.k=B6.prototype;g.k.yj=null;g.k.ag=!1;g.k.Zl=null;g.k.ox=null;g.k.Ml=null;g.k.Sl=null;g.k.Wh=null;g.k.Qi=null;g.k.hk=null;g.k.dd=null;g.k.yo=0;g.k.gg=null;g.k.ws=null;g.k.li=null;g.k.Um=-1;g.k.ID=!0;g.k.fj=!1;g.k.ru=0;g.k.Cr=null;var DAa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.vO=function(a){a=a.target;var b=this.Cr;b&&3==S6(a)?b.QA():this.HE(a)};
g.k.HE=function(a){try{if(a==this.dd)a:{var b=S6(this.dd),c=this.dd.F,d=this.dd.getStatus();if(g.me&&!g.Qd(10)||g.oe&&!g.Pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!U6(this.dd))break a;this.fj||4!=b||7==c||(8==c||0>=d?this.o.Sf(3):this.o.Sf(2));L6(this);var e=this.dd.getStatus();this.Um=e;var f=U6(this.dd);(this.ag=200==e)?(4==b&&H6(this),this.F?(EAa(this,b,f),g.Dh&&this.ag&&3==b&&(this.B.ma(this.u,"tick",this.pO),this.u.start())):G6(this,f),this.ag&&!this.fj&&(4==b?this.o.Zp(this):(this.ag=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.li=3,F6(13)):(this.li=0,F6(14)),H6(this),I6(this))}}catch(h){this.dd&&U6(this.dd)}finally{}};
g.k.pO=function(){var a=S6(this.dd),b=U6(this.dd);this.yo<b.length&&(L6(this),EAa(this,a,b),this.ag&&4!=a&&D6(this))};
g.k.JN=function(a){K6((0,g.x)(this.IN,this,a),0)};
g.k.IN=function(a){this.fj||(L6(this),G6(this,a),D6(this))};
g.k.MC=function(a){K6((0,g.x)(this.HN,this,a),0)};
g.k.HN=function(a){this.fj||(H6(this),this.ag=a,this.o.Zp(this),this.o.Sf(4))};
g.k.cancel=function(){this.fj=!0;H6(this)};
g.k.TN=function(){this.Zl=null;var a=(0,g.E)();0<=a-this.ox?(2!=this.Sl&&this.o.Sf(3),H6(this),this.li=2,F6(18),I6(this)):HAa(this,this.ox-a)};
g.k.getLastError=function(){return this.li};g.k=KAa.prototype;g.k.pu=null;g.k.ze=null;g.k.Dr=!1;g.k.Tz=null;g.k.Fp=null;g.k.Tu=null;g.k.qu=null;g.k.ff=null;g.k.ph=-1;g.k.Tm=null;g.k.om=null;g.k.connect=function(a){this.qu=a;a=N6(this.o,null,this.qu);F6(3);this.Tz=(0,g.E)();var b=this.o.I;null!=b?(this.Tm=b[0],(this.om=b[1])?(this.ff=1,LAa(this)):(this.ff=2,P6(this))):(b6(a,"MODE","init"),this.ze=new B6(this,void 0,void 0,void 0),this.ze.yj=this.pu,C6(this.ze,a,!1,null,!0),this.ff=0)};
g.k.NF=function(a){if(a)this.ff=2,P6(this);else{F6(4);var b=this.o;b.sg=b.Zh.ph;a7(b,9)}a&&this.Sf(2)};
g.k.Jt=function(a){return this.o.Jt(a)};
g.k.abort=function(){this.ze&&(this.ze.cancel(),this.ze=null);this.ph=-1};
g.k.Sz=function(){return!1};
g.k.DC=function(a,b){this.ph=a.Um;if(0==this.ff)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.sg=this.ph;a7(c,2);return}this.Tm=c[0];this.om=c[1]}else c=this.o,c.sg=this.ph,a7(c,2);else if(2==this.ff)if(this.Dr)F6(7),this.Tu=(0,g.E)();else if("11111"==b){if(F6(6),this.Dr=!0,this.Fp=(0,g.E)(),c=this.Fp-this.Tz,!g.me||g.Qd(10)||500>c)this.ph=200,this.ze.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Fp=this.Tu=(0,g.E)(),this.Dr=!1};
g.k.Zp=function(){this.ph=this.ze.Um;if(this.ze.ag)0==this.ff?this.om?(this.ff=1,LAa(this)):(this.ff=2,P6(this)):2==this.ff&&((!g.me||g.Qd(10)?!this.Dr:200>this.Tu-this.Fp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.ff?F6(9):2==this.ff&&F6(10);var a=this.o;this.ze.getLastError();a.sg=this.ph;a7(a,2)}};
g.k.jo=function(){return this.o.jo()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Sf=function(a){this.o.Sf(a)};g.Ua(Q6,g.nf);var QAa=/^https?$/i,DCa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Y=!1;this.A=!0;this.o=this.T?zAa(this.T):zAa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.zC,this);try{d6(T6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));PAa(this,f);return}a=
c||"";var e=this.headers.clone();d&&Zza(d,function(f,h){e.set(h,f)});
d=g.cb(e.cf(),NAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(DCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{SAa(this),0<this.G&&(this.R=MAa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Uz,this)):this.N=g.Zf(this.Uz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),PAa(this,f)}};
g.k.Uz=function(){"undefined"!=typeof g.D1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.tc.X.call(this)};
g.k.zC=function(){this.ha()||(this.aa||this.I||this.C?RAa(this):this.QM())};
g.k.QM=function(){RAa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Xk=null;g.k.Im=null;g.k.le=null;g.k.Ec=null;g.k.ou=null;g.k.Ip=null;g.k.uy=null;g.k.Yp=null;g.k.Cn=0;g.k.uK=0;g.k.Id=null;g.k.di=null;g.k.Yg=null;g.k.kj=null;g.k.Zh=null;g.k.ts=null;g.k.ol=-1;g.k.BA=-1;g.k.sg=-1;g.k.Qk=0;g.k.Ck=0;g.k.gj=8;var b7=new g.nf;g.Ua(UAa,g.Ne);g.Ua(VAa,g.Ne);g.Ua(WAa,g.Ne);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.ou=b;this.Im=c||{};d&&void 0!==e&&(this.Im.OSID=d,this.Im.OAID=e);this.F?(K6((0,g.x)(this.My,this,a),100),$Aa(this)):this.My(a)};
g.k.My=function(a){this.Zh=new KAa(this);this.Zh.pu=this.Xk;this.Zh.u=this.C;this.Zh.connect(a)};
g.k.Sz=function(){return 0==this.o};
g.k.LC=function(a){this.di=null;cBa(this,a)};
g.k.KC=function(){this.Yg=null;this.Ec=new B6(this,this.A,"rpc",this.G);this.Ec.yj=this.Xk;this.Ec.ru=0;var a=this.uy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.ts?"0":"1");$5(a,"AID",this.ol);W6(this,a);if(!g.me||g.Qd(10))$5(a,"TYPE","xmlhttp"),C6(this.Ec,a,!0,this.Yp,!1);else{$5(a,"TYPE","html");var b=this.Ec,c=!!this.Yp;b.Sl=3;b.Wh=a6(a.clone());GAa(b,c)}};
g.k.DC=function(a,b){if(0!=this.o&&(this.Ec==a||this.le==a))if(this.sg=a.Um,this.le==a&&3==this.o)if(7<this.gj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Yg){if(this.Ec)if(this.Ec.Ml+3E3<this.le.Ml)Y6(this),this.Ec.cancel(),this.Ec=null;else break a;$6(this);F6(19)}}else this.BA=c[1],0<this.BA-this.ol&&37500>c[2]&&this.ts&&0==this.Ck&&!this.kj&&(this.kj=K6((0,g.x)(this.VK,this),6E3));else a7(this,11)}else b!=CCa.OQ.o&&a7(this,11);else if(this.Ec==
a&&Y6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ol=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Yp=e[2],e=e[3],null!=e?this.gj=e:this.gj=6,this.o=3,this.Id&&this.Id.Hy(),this.uy=N6(this,this.jo()?this.Yp:null,this.ou),dBa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Id&&this.Id.Gy(e),this.Ck=0)}}};
g.k.VK=function(){null!=this.kj&&(this.kj=null,this.Ec.cancel(),this.Ec=null,$6(this),F6(20))};
g.k.Zp=function(a){if(this.Ec==a){Y6(this);this.Ec=null;var b=2}else if(this.le==a)this.le=null,b=1;else return;this.sg=a.Um;if(0!=this.o)if(a.ag)1==b?(b=(0,g.E)()-a.Ml,b7.dispatchEvent(new VAa(b7,a.hk?a.hk.length:0,b,this.Qk)),X6(this),this.B.length=0):dBa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.sg)){if(d=1==b)this.le||this.di||1==this.o||2<=this.Qk?d=!1:(this.di=K6((0,g.x)(this.LC,this,a),eBa(this,this.Qk)),this.Qk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.nG=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.eP=function(a){a?F6(2):(F6(1),fBa(this,8))};
g.k.Jt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Id&&this.Id.isActive(this)};
g.k.Sf=function(a){b7.dispatchEvent(new WAa(b7,a))};
g.k.jo=function(){return!(!g.me||g.Qd(10))};
g.k=gBa.prototype;g.k.Hy=function(){};
g.k.Gy=function(){};
g.k.Fy=function(){};
g.k.xt=function(){};
g.k.qz=function(){return{}};
g.k.isActive=function(){return!0};g.k=hBa.prototype;g.k.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Bua)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.u,a)};
g.k.Wd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(c7,g.A);g.k=c7.prototype;g.k.CN=function(){this.Ld=Math.min(3E5,2*this.Ld);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Ld+15E3*Math.random();this.o.jb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Ld=5E3};g.Ua(d7,gBa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Hi=function(a){return this.A.zj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Rc||(this.Rc=!0,g.Le(this.A),kBa(this),g.Le(this.u),this.u=null,this.R=function(){return""})};
g.k.ha=function(){return this.Rc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Id=null);d.Id=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.A,e.ol):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Xb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&(e7(this),aBa(this.o,c))};
g.k.Hy=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)aBa(this.o,a[b])}this.S("handlerOpened")};
g.k.Fy=function(a){var b=2==a&&401==this.o.sg;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.xt=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.qz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Xb(a,this.C);return a};
g.k.Gy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),ZAa(this.o)):this.S("handlerMessage",new iBa(a[0],a[1]))};
g.k.JO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.le&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var sBa=(0,g.E)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Ua(o7,g.O);o7.prototype.Le=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.O);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.ME()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Mo(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.O.prototype.X.call(this)};
g.k.ME=function(){this.Ka=NaN;this.o=g.uq(h7(this.F,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.HP,this),onError:(0,g.x)(this.GP,this),Re:(0,g.x)(this.IP,this)})};
g.k.HP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new g6(c))};
g.k.GP=function(a){this.o=null;a.status&&404==a.status?this.u>=ECa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=ECa[this.u],this.Ka=g.Ko((0,g.x)(this.ME,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.IP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var ECa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.S("screenChange");!g.ft("yt-remote-lounge-token-expiration")&&wBa(this);g.Mo(this.o);this.o=g.Ko((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);tBa(this,a);s7(this,!1);this.S("screenChange");b(a);a.token||wBa(this)};
g.k.remove=function(a,b){var c=q7(this);vBa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.qs=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Mo(this.o);r7.tc.X.call(this)};
g.k.aH=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.ZG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.O);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.ft("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?w7(this):(this.B=(0,g.E)()+3E5,g.et("yt-remote-fast-check-period",this.B),this.mw())};
g.k.isEmpty=function(){return g.Rb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Cb(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.X=function(){g.Mo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.X.call(this)};
g.k.mw=function(){g.Mo(this.A);this.A=NaN;this.u&&this.u.abort();var a=zBa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.x)(this.mN,this,a),(0,g.x)(this.lN,this))}else v7(this,{}),w7(this)};
g.k.mN=function(a,b){this.u=null;var c=g.Kb(zBa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.pc("Changing Screen set during request."),this.mw()};
g.k.lN=function(a){this.pc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.pc=function(a){k7("OnlineScreenService",a)};g.Ua(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.qs=function(a,b,c,d){this.u.contains(a)?this.u.qs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Le=function(a){return a?this.screens:g.ob(this.screens,(0,g.ze)(this.A,function(b){return!this.contains(b)},this))};
g.k.NE=function(){return(0,g.ze)(this.Le(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.OE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Le(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Le(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.KP=function(a,b,c,d){g.uq(h7(this.C,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||DBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);DBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Re:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Le(this.u);g.Le(this.o);x7.tc.X.call(this)};
g.k.hH=function(){EBa(this);this.S("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Ua(A7,g.O);g.k=A7.prototype;g.k.getScreen=function(){return this.I};
g.k.sr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Qe=function(a){this.ha()||(a&&B7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.QE=function(){return null};
g.k.yw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.yw("");A7.tc.X.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.xw=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);GBa(this)};
g.k.pl=function(a){this.info("launchWithParams no-op for Cast: "+g.Ok(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Qe()},this),(0,g.x)(function(){this.Qe(Error("Failed to stop receiver app."))},this)):this.Qe(Error("Stopping cast device witout session."))};
g.k.yw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Mo(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.X.call(this)};
g.k.bO=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ok(c));switch(d){case "mdxSessionStatus":FBa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.Lz=function(a,b,c,d){CBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ko((0,g.x)(this.Lz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.QE=function(){return this.u};
g.k.LP=function(a){this.ha()||a||(B7(this,"Cast session died."),this.Qe())};g.t(D7,A7);g.k=D7.prototype;g.k.xw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.pl=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.Mo(this.C);this.A?this.A.stop((0,g.x)(this.Qe,this,null),(0,g.x)(this.Qe,this,"Failed to stop DIAL device.")):this.Qe()};
g.k.X=function(){this.u();this.u=g.Ka;g.Mo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;A7.prototype.X.call(this)};
g.k.OP=function(a){this.ha()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Qe())};
g.k.Cu=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,IBa(this));a(b);HBa(this)}else this.F=(0,g.x)(function(){g.Mo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,IBa(this));a(c);HBa(this)},this),this.C=g.Ko((0,g.x)(function(){this.F()},this),100)};
g.k.xH=function(a,b,c){CBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.sr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Cu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.Cu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Qe()};
E7.prototype.xw=function(){};
E7.prototype.pl=function(){g.Mo(this.u);this.u=NaN;var a=m6(this.M.Le(),this.o.label);a?this.sr(a):this.Qe(Error("No such screen"))};
E7.prototype.X=function(){g.Mo(this.u);this.u=NaN;A7.prototype.X.call(this)};g.t(F7,g.O);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.VM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.GC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.qL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),pBa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.PE,this)),this.A=KBa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.pc("Failed to set initial custom receivers: "+g.Ok(h))},this)),this.S("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.pc("Failed to initialize API: "+g.Ok(h));
b(!1)},this))};
g.k.PO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Le(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=JBa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.Ok(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.yw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.QO=function(a){this.ha()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.pl(a):this.pc("Setting connection data without a session")};
g.k.NP=function(){this.ha()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.GC,this),(0,g.x)(this.pN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.PE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=mBa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Le(this.o);g.O.prototype.X.call(this)};
g.k.pc=function(a){k7("Controller",a)};
g.k.IC=function(a,b){this.o==a&&(b||I7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.RM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.k.qL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.xH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Cu,b))};
g.k.GC=function(a){if(!this.ha()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Le(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Le(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.IC,this,this.o)),this.o.pl(null));this.o.xw(a)}}};
g.k.MP=function(){return this.o?this.o.QE():null};
g.k.pN=function(a){this.ha()||(this.pc("Failed to estabilish a session: "+g.Ok(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.VM=function(a){G7("Receiver availability updated: "+a);if(!this.ha()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.S("yt-remote-cast2-availability-change",H7(this))}};
g.k.PE=function(){this.ha()||(this.A=KBa(this),G7("Updating custom receivers: "+g.Ok(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.QO;F7.prototype.setConnectedScreenStatus=F7.prototype.PO;F7.prototype.stopSession=F7.prototype.NP;F7.prototype.getCastSession=F7.prototype.MP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.tg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.ub=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.O);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ub()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.S("remotePlayerChange")}else c8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.S("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Sa(this.setVolume,a,b))};
g.k.LE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ok(b.style),g.Xb(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Sa(this.LE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Ok(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.yr=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Sa(this.yr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Sa(this.nextVideo,a,b))};
g.k.Zy=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.Zy)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.k.X=function(){XBa(this);this.B=null;this.C.clear();$7(this,null);g.O.prototype.X.call(this)};
g.k.sx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.OM=function(a,b){this.S(a,b)};
g.k.bL=function(a){if(!a)this.Gn(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Gn=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),YBa(this),this.S("remotePlayerChange")};
g.k.aL=function(a){a?(YBa(this),this.S("remotePlayerChange")):this.Gn(null)};
g.k.Rw=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.jL=function(){var a=UBa();a&&$7(this,a)};
g.k.pc=function(a){k7("CP",a)};g.t(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;W7(this.ib,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Ok(l));this.o.connect({method:"setPlaylist",
params:g.Ok(l)},a,kAa())}else i8("Connecting without params"),this.o.connect({},a,kAa());$Ba(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.X=function(){k8(this);m8(this);l8(this);g.Mo(this.G);this.G=NaN;g.Mo(this.I);this.I=NaN;this.A=null;g.hp(this.U);this.U.length=0;this.o.dispose();g.O.prototype.X.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.TG=function(){this.Lk(2)};
g.k.fL=function(){i8("Channel opened");this.R&&(this.R=!1,l8(this),this.N=g.Ko((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Lk(1)},this),15E3));
oAa(jBa(this.o),this.T)};
g.k.cL=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.dL=function(a){r6();isNaN(this.Pm())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,i8("Channel error: "+a+" with reconnection in "+this.Pm()+" ms"),j8(this,2))};
g.k.eL=function(a){a.params?i8("Received: action="+a.action+", params="+g.Ok(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new f6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
cCa(this,a);break;case "loungeScreenDisconnected":g.nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
cCa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||Vza(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.nb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":eCa(this,a);break;case "nowPlaying":gCa(this,a);break;case "onStateChange":fCa(this,a);break;case "onAdStateChange":hCa(this,a);break;case "onVolumeChanged":iCa(this,a);break;case "onSubtitlesTrackChanged":dCa(this,a);break;case "nowAutoplaying":jCa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":kCa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.FO=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.IG=function(){var a=3;this.ha()||(a=0,isNaN(this.Pm())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Lk=function(a){i8("Disconnecting with "+a);k8(this);this.S("beforeDisconnect",a);1==a&&r6();kBa(this.o,a);this.dispose()};
g.k.GG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.RO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.Mo(this.G),this.G=g.Ko((0,g.x)(this.FO,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&X7(this.ib)==X7(b)&&g.Ok(this.ib.o)==g.Ok(b.o)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.Jz=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Pm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.vG=function(){return this.B||"UNSUPPORTED"};
g.k.wG=function(){return this.F||""};
g.k.FP=function(){if(!isNaN(this.Pm())){var a=this.o.u;g.Cn(a.o);a.start()}};
g.k.NO=function(a,b){n8(this,a,b);bCa(this)};
g.k.KE=function(){var a=g.Dq("SID","")||"",b=g.Dq("SAPISID","")||"";if(!a&&!b)return"";a=g.wg(g.dg(a),2);b=g.wg(g.dg(b),2);return g.wg(g.dg(a+","+b),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Hi;h8.prototype.getProxyState=h8.prototype.IG;h8.prototype.disconnect=h8.prototype.Lk;h8.prototype.getPlayerContextData=h8.prototype.GG;h8.prototype.setPlayerContextData=h8.prototype.RO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.Jz;h8.prototype.getReconnectTimeout=h8.prototype.Pm;h8.prototype.getAutoplayMode=h8.prototype.vG;h8.prototype.getAutoplayVideoId=h8.prototype.wG;h8.prototype.reconnect=h8.prototype.FP;
h8.prototype.sendMessage=h8.prototype.NO;h8.prototype.getXsrfToken=h8.prototype.KE;g.t(o8,o7);g.k=o8.prototype;g.k.Le=function(a){return this.Kd.$_gs(a)};
g.k.contains=function(a){return!!this.Kd.$_c(a)};
g.k.get=function(a){return this.Kd.$_g(a)};
g.k.start=function(){this.Kd.$_st()};
g.k.add=function(a,b,c){this.Kd.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Kd.$_r(a,b,c)};
g.k.qs=function(a,b,c,d){this.Kd.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Kd.$_ubk(this.o[a]);this.o.length=0;this.Kd=null;o7.prototype.X.call(this)};
g.k.JP=function(){this.S("screenChange")};
g.k.rM=function(){this.S("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.KP;x7.prototype.$_gsppc=x7.prototype.OE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.qs;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Le;x7.prototype.$_gos=x7.prototype.NE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Hi;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.A);g.k=I8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.ab;a.unsubscribe("proxyStateChange",this.CC,this);a.unsubscribe("remotePlayerChange",this.Mn,this);a.unsubscribe("remoteQueueChange",this.tr,this);a.unsubscribe("previousNextChange",this.yC,this);a.unsubscribe("nowAutoplaying",this.uC,this);a.unsubscribe("autoplayDismissed",this.UB,this);this.ab=this.module=null};
g.k.gB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ab.o)if(J8(this)){if(!b8(this.ab).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.ab).ub()?this.ab.pause():this.ab.play();break;case "control_play":this.ab.play();break;case "control_pause":this.ab.pause();break;case "control_seek":this.F.QA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.ZK=function(a){this.G.OG(a)};
g.k.oP=function(a){this.gB("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.WD=function(){var a=this.H.getOption("captions","track");g.Rb(a)||K8(this,a)};
g.k.Xb=function(a){this.module.Xb(a,this.H.getVideoData().lengthSeconds)};
g.k.kC=function(a){if(J8(this)){this.ab.unsubscribe("remotePlayerChange",this.Mn,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.ab);if(b!==c.volume||a!==c.muted)this.ab.setVolume(b,a),this.I.start();this.ab.subscribe("remotePlayerChange",this.Mn,this)}};
g.k.SL=function(){g.Rb(this.A)||wCa(this,this.A);this.B=!1};
g.k.CC=function(a,b){this.u.stop();2===b&&this.TD()};
g.k.Mn=function(){if(J8(this)){this.o.stop();var a=b8(this.ab);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.kd=1;break;case 1082:case 1083:this.module.kd=0;break;default:this.module.kd=-1}switch(a.playerState){case 1081:case 1:this.Pc(new g.fG(8));this.SD();break;case 1085:case 3:this.Pc(new g.fG(9));break;case 1083:case 0:this.Pc(new g.fG(2));this.F.stop();this.Xb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Pc(new g.fG(4));break;case 2:this.Pc(new g.fG(4));
this.Xb(X7(a));break;case -1:this.Pc(new g.fG(64));break;case -1E3:this.Pc(new g.fG(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=b8(this.ab).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,wCa(this,a));a=b8(this.ab);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.wE()}else vCa(this)};
g.k.yC=function(){this.H.S("mdxpreviousnextchange")};
g.k.tr=function(){J8(this)||vCa(this)};
g.k.uC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.UB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.ab.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.ab).playerState?L8(this,a):b&&this.ab.seekTo(a)};
g.k.wE=function(){if(J8(this)){var a=b8(this.ab);this.events.rb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.kC)}};
g.k.SD=function(){this.o.stop();if(!this.ab.ha()){var a=b8(this.ab);a.ub()&&this.Pc(new g.fG(8));this.Xb(X7(a));this.o.start()}};
g.k.TD=function(){this.u.stop();this.o.stop();var a=this.ab.B.getReconnectTimeout();2==this.ab.o&&!isNaN(a)&&this.u.start()};
g.k.Pc=function(a){this.u.stop();var b=this.C;if(!g.kG(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.dU(this.H.app,c);this.C=a;yCa(this.module,b,a)}};g.t(M8,g.U);M8.prototype.Yb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){g.xO("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(N8,g.U);N8.prototype.Yb=function(){this.o.show()};
N8.prototype.Sa=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(O8,g.U);O8.prototype.u=function(a){xCa(this,a.state)};g.t(P8,g.LR);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Pi=g.Ab(a,this.o,this),g.NR(this,(0,g.Ic)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Ob(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Qf=function(a){return"cast-selector-receiver"===a?"Reparto...":this.Pi[a].name};
P8.prototype.wd=function(a){g.LR.prototype.wd.call(this,a);this.H.setOption("remote","currentReceiver",this.Pi[a]);this.Ma.Sa()};g.t(Q8,g.WN);g.k=Q8.prototype;
g.k.create=function(){pCa(g.ty(this.player.O()));this.subscriptions.push(g.Ro("yt-remote-before-disconnect",this.XK,this));this.subscriptions.push(g.Ro("yt-remote-connection-change",this.WM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-availability-change",this.AC,this));this.subscriptions.push(g.Ro("yt-remote-auto-connect",this.UM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-resumed",this.TM,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-confirm",this.tO,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-cancel",
this.sO,this));this.subscriptions.push(g.Ro("mdx-manual-pairing-popup-ok",this.PH,this));this.AC()};
g.k.load=function(){this.player.cancelPlayback();g.WN.prototype.load.call(this);this.lg=new I8(this,this.player,this.ab);var a=(a=uCa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Xb(a);yCa(this,this.Tb,this.Tb);g.kU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.bi=this.Nf;g.Me(this.lg,this.ab);this.ab=this.lg=null;g.WN.prototype.unload.call(this);g.kU(this.player.app,5);R8(this)};
g.k.X=function(){g.So(this.subscriptions);g.WN.prototype.X.call(this)};
g.k.Gg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.lg.gB.apply(this.lg,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.kd};
g.k.KG=function(){return this.loaded?this.lg.suggestion:null};
g.k.tg=function(){return this.ab?b8(this.ab).tg:!1};
g.k.hasNext=function(){return this.ab?b8(this.ab).hasNext:!1};
g.k.Xb=function(a,b){this.CA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.CA};
g.k.getProgressState=function(){var a=b8(this.ab),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.jd():!a.isAdPlaying()&&this.player.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.ab&&this.ab.nextVideo()};
g.k.yr=function(){this.ab&&this.ab.yr()};
g.k.XK=function(a){1===a&&(this.Xv=this.ab?b8(this.ab):null)};
g.k.WM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.bi;this.loaded&&this.unload();this.ab=a;this.Xv=null;b.key!==this.Nf.key&&(this.bi=b,this.load())}else g.Le(this.ab),this.ab=null,this.loaded&&(this.unload(),(a=this.Xv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.AC=function(){this.Pi=[this.Nf].concat(rCa());var a=A8()||this.Nf;S8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.UM=function(){var a=A8();S8(this,a)};
g.k.TM=function(){this.bi=A8()};
g.k.tO=function(){this.Nn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.sO=function(){this.Nn=!1;R8(this);S8(this,this.Nf);this.bi=this.Nf;G8=!1;H8=null;this.player.playVideo()};
g.k.PH=function(){this.Bq=!0;R8(this);g.et("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.fd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Pi;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.bi:this.Nf;case "quickCast":return 2===this.Pi.length&&"cast-selector-receiver"===this.Pi[1].key?(b&&R7(),!0):!1}};
g.k.Rw=function(){this.ab.Rw()};
g.k.Zf=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.gO.remote=Q8;})(_yt_player);
