(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(a){function b(h,n){if("function"===typeof window.CustomEvent)return new CustomEvent(h,n);var r=document.createEvent("CustomEvent");r.initCustomEvent(h,!!n.bubbles,!!n.cancelable,n.detail);return r}function c(h){if(Q)return h.ownerDocument!==document?h.ownerDocument:null;var n=h.__importDoc;if(!n&&h.parentNode){n=h.parentNode;if("function"===typeof n.closest)n=n.closest("link[rel=import]");else for(;!k(n)&&(n=n.parentNode););h.__importDoc=n}return n}function d(h){var n=q(document,"link[rel=import]:not([import-dependency])"),
r=n.length;r?w(n,function(t){return g(t,function(){0===--r&&h()})}):h()}function e(h){function n(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",n),h())}document.addEventListener("readystatechange",n);n()}function f(h){e(function(){return d(function(){return h&&h()})})}function g(h,n){if(h.__loaded)n&&n();else if("script"===h.localName&&!h.src||"style"===h.localName&&!h.firstChild||"style"===h.localName&&"http://www.w3.org/2000/svg"===h.namespaceURI)h.__loaded=
!0,n&&n();else{var r=function(t){h.removeEventListener(t.type,r);h.__loaded=!0;n&&n()};h.addEventListener("load",r);"style"===h.localName&&(Ta||ta)||h.addEventListener("error",r)}}function k(h){return h.nodeType===Node.ELEMENT_NODE&&"link"===h.localName&&"import"===h.rel}function m(){var h=this;this.B={};this.L=0;this.ma=new MutationObserver(function(n){return h.Xb(n)});this.ma.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function p(h){w(q(h,"template"),function(n){w(q(n.content,
'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(r){var t=document.createElement("script");w(r.attributes,function(z){return t.setAttribute(z.name,z.value)});t.textContent=r.textContent;r.parentNode.replaceChild(t,r)});p(n.content)})}function q(h,n){return h.childNodes.length?h.querySelectorAll(n):Cd}function w(h,n,r){var t=h?h.length:0,z=r?-1:1;for(r=r?t-1:0;r<t&&0<=r;r+=z)n(h[r],r)}var B=document.createElement("link"),Q="import"in
B,Cd=B.querySelectorAll("*"),Ua=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return Ua||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Dd=/(url\()([^)]*)(\))/g,Ed=/(@import[\s]+(?!url\())([^;]*)(;)/g,Fd=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,L={Vb:function(h,n){h.href&&h.setAttribute("href",L.ba(h.getAttribute("href"),n));h.src&&h.setAttribute("src",L.ba(h.getAttribute("src"),
n));if("style"===h.localName){var r=L.Qa(h.textContent,n,Dd);h.textContent=L.Qa(r,n,Ed)}},Qa:function(h,n,r){return h.replace(r,function(t,z,v,A){t=v.replace(/["']/g,"");n&&(t=L.ba(t,n));return z+"'"+t+"'"+A})},ba:function(h,n){if(void 0===L.da){L.da=!1;try{var r=new URL("b","http://a");r.pathname="c%20d";L.da="http://a/c%20d"===r.href}catch(t){}}if(L.da)return(new URL(h,n)).href;r=L.$a;r||(r=document.implementation.createHTMLDocument("temp"),L.$a=r,r.sa=r.createElement("base"),r.head.appendChild(r.sa),
r.ra=r.createElement("a"));r.sa.href=n;r.ra.href=h;return r.ra.href||h}},Sb={async:!0,load:function(h,n,r){if(h)if(h.match(/^data:/)){h=h.split(",");var t=h[1];t=-1<h[0].indexOf(";base64")?atob(t):decodeURIComponent(t);n(t)}else{var z=new XMLHttpRequest;z.open("GET",h,Sb.async);z.onload=function(){var v=z.responseURL||z.getResponseHeader("Location");v&&0===v.indexOf("/")&&(v=(location.origin||location.protocol+"//"+location.host)+v);var A=z.response||z.responseText;304===z.status||0===z.status||200<=
z.status&&300>z.status?n(A,v):r(A)};z.send()}else r("error: href must be specified")}},Ta=/Trident/.test(navigator.userAgent),ta=/Edge\/\d./i.test(navigator.userAgent);m.prototype.loadImports=function(h){var n=this;h=q(h,"link[rel=import]");w(h,function(r){return n.Na(r)})};m.prototype.Na=function(h){var n=this,r=h.href;if(void 0!==this.B[r]){var t=this.B[r];t&&t.__loaded&&(h.__import=t,this.La(h))}else this.L++,this.B[r]="pending",Sb.load(r,function(z,v){z=n.cc(z,v||r);n.B[r]=z;n.L--;n.loadImports(z);
n.Pa()},function(){n.B[r]=null;n.L--;n.Pa()})};m.prototype.cc=function(h,n){var r=this;if(!h)return document.createDocumentFragment();if(Ta||ta)h=h.replace(Fd,function(v,A,ua){return-1===v.indexOf("type=")?A+" type=import-disable "+ua:v});var t=document.createElement("template");t.innerHTML=h;if(t.content)h=t.content,p(h);else for(h=document.createDocumentFragment();t.firstChild;)h.appendChild(t.firstChild);if(t=h.querySelector("base"))n=L.ba(t.getAttribute("href"),n),t.removeAttribute("href");t=
q(h,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var z=0;w(t,function(v){g(v);L.Vb(v,n);if("style"===v.localName&&r.Sa(v)){var A=r.Rb(v);g(A);v.parentNode.replaceChild(A,v);v=A}v.setAttribute("import-dependency","");if("script"===v.localName&&!v.src&&v.textContent){if("module"===v.type)throw Error("Inline module scripts are not supported in HTML Imports.");
v.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(v.textContent+("\n//# sourceURL="+n+(z?"-"+z:"")+".js\n")));v.textContent="";z++}});return h};m.prototype.Sa=function(h){return ta&&-1<h.textContent.indexOf("@import")};m.prototype.Rb=function(h){var n=h.ownerDocument.createElement("style");n.textContent=h.textContent;w(h.attributes,function(r){return n.setAttribute(r.name,r.value)});return n};m.prototype.Pa=function(){var h=this;if(!this.L){this.ma.disconnect();this.flatten(document);
var n=!1,r=!1,t=function(){r&&n&&(h.loadImports(document),h.L||(h.ma.observe(document.head,{childList:!0,subtree:!0}),h.Ub()))};this.oc(function(){r=!0;t()});this.hc(function(){n=!0;t()})}};m.prototype.flatten=function(h){var n=this;h=q(h,"link[rel=import]");w(h,function(r){var t=n.B[r.href];(r.__import=t)&&t.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(n.B[r.href]=r,r.readyState="loading",r.__import=r,n.flatten(t),r.appendChild(t))})};m.prototype.hc=function(h){function n(z){if(z<t){var v=r[z],A=document.createElement("script");
v.removeAttribute("import-dependency");w(v.attributes,function(ua){return A.setAttribute(ua.name,ua.value)});Ua=A;v.parentNode.replaceChild(A,v);g(A,function(){Ua=null;n(z+1)})}else h()}var r=q(document,"script[import-dependency]"),t=r.length;n(0)};m.prototype.oc=function(h){var n=this,r=q(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),t=r.length;if(t){var z=(Ta||ta)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");w(r,function(v){z&&n.Sa(v)&&
v.ownerDocument.defaultView!==window.top&&(v.__loaded=!0);g(v,function(){v.removeAttribute("import-dependency");0===--t&&h()});if(z&&v.parentNode!==document.head){var A=document.createElement(v.localName);A.__appliedElement=v;A.setAttribute("type","import-placeholder");v.parentNode.insertBefore(A,v.nextSibling);for(A=c(v);A&&c(A);)A=c(A);A.parentNode!==document.head&&(A=null);document.head.insertBefore(v,A);v.removeAttribute("type")}})}else h()};m.prototype.Ub=function(){var h=this,n=q(document,"link[rel=import]");
w(n,function(r){return h.La(r)},!0)};m.prototype.La=function(h){h.__loaded||(h.__loaded=!0,h.import&&(h.import.readyState="complete"),h.dispatchEvent(b(h.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};m.prototype.Xb=function(h){var n=this;w(h,function(r){return w(r.addedNodes,function(t){t&&t.nodeType===Node.ELEMENT_NODE&&(k(t)?n.Na(t):n.loadImports(t))})})};var Va=null;if(Q)B=q(document,"link[rel=import]"),w(B,function(h){h.import&&"loading"===h.import.readyState||(h.__loaded=
!0)}),B=function(h){h=h.target;k(h)&&(h.__loaded=!0)},document.addEventListener("load",B,!0),document.addEventListener("error",B,!0);else{var ka=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!ka||ka.configurable?Node:Element).prototype,"baseURI",{get:function(){var h=k(this)?this:c(this);return h?h.href:ka&&ka.get?ka.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,
"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){Va=new m})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=Q;a.whenReady=f;a.importForElement=c;a.loadImports=function(h){Va&&Va.loadImports(h)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function fa(){}fa.prototype.toJSON=function(){return{}};function u(a){a.__shady||(a.__shady=new fa);return a.__shady}function x(a){return a&&a.__shady};var y=window.ShadyDOM||{};y.Yb=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ha=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");y.h=!!(ha&&ha.configurable&&ha.get);y.na=y.force||!y.Yb;y.l=y.noPatch||!1;y.N=y.preferPerformance;y.pa="on-demand"===y.l;var ia=navigator.userAgent.match("Trident");y.Va=ia;function C(a){return(a=x(a))&&void 0!==a.firstChild}function D(a){return a instanceof ShadowRoot}function ja(a){return(a=(a=x(a))&&a.root)&&a.ya()}
var E=Element.prototype,la=E.matches||E.matchesSelector||E.mozMatchesSelector||E.msMatchesSelector||E.oMatchesSelector||E.webkitMatchesSelector,ma=document.createTextNode(""),na=0,oa=[];(new MutationObserver(function(){for(;oa.length;)try{oa.shift()()}catch(a){throw ma.textContent=na++,a;}})).observe(ma,{characterData:!0});function pa(a){oa.push(a);ma.textContent=na++}var qa=document.contains?function(a,b){return a.__shady_native_contains(b)}:function(a,b){return a===b||a.documentElement&&a.documentElement.__shady_native_contains(b)};
function ra(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}function sa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ba(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}
function va(a){var b=[];for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)b.push(a);return b}function wa(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b.push(a);return b}function xa(a,b,c){c.configurable=!0;if(c.value)a[b]=c.value;else try{Object.defineProperty(a,b,c)}catch(d){}}function F(a,b,c,d){c=void 0===c?"":c;for(var e in b)d&&0<=d.indexOf(e)||xa(a,c+e,b[e])}function ya(a,b){for(var c in b)c in a&&xa(a,c,b[c])}
function G(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b}function za(a,b){for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length;d++)e=c[d],a[e]=b[e]};var Aa=[],Ba;function Ca(a){Ba||(Ba=!0,pa(Da));Aa.push(a)}function Da(){Ba=!1;for(var a=!!Aa.length;Aa.length;)Aa.shift()();return a}Da.list=Aa;function Ea(){this.U=!1;this.addedNodes=[];this.removedNodes=[];this.Y=new Set}function Fa(a){a.U||(a.U=!0,pa(function(){a.flush()}))}Ea.prototype.flush=function(){if(this.U){this.U=!1;var a=this.takeRecords();a.length&&this.Y.forEach(function(b){b(a)})}};Ea.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ga(a,b){var c=u(a);c.M||(c.M=new Ea);c.M.Y.add(b);var d=c.M;return{cb:b,zb:d,yb:a,takeRecords:function(){return d.takeRecords()}}}function Ha(a){var b=a&&a.zb;b&&(b.Y.delete(a.cb),b.Y.size||(u(a.yb).M=null))}
function Ia(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=[].slice.call(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ja=/[&\u00A0"]/g,Ka=/[&\u00A0<>]/g;function La(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ma(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Na=Ma("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Oa=Ma("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Pa(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var k=g;var m=a,p=b;switch(k.nodeType){case Node.ELEMENT_NODE:m=k.localName;for(var q="<"+m,w=k.attributes,B=0,Q;Q=w[B];B++)q+=" "+Q.name+'="'+Q.value.replace(Ja,La)+'"';q+=">";k=Na[m]?q:q+Pa(k,p)+"</"+m+">";break a;case Node.TEXT_NODE:k=k.data;k=m&&Oa[m.localName]?k:k.replace(Ka,La);break a;case Node.COMMENT_NODE:k="\x3c!--"+k.data+"--\x3e";break a;default:throw window.console.error(k),
Error("not implemented");}}c+=k}return c};var Qa=y.h,Ra={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Sa={};function Wa(a){Sa[a]=function(b){return b["__shady_native_"+a]}}function Xa(a,b){F(a,b,"__shady_native_");for(var c in b)Wa(c)}function H(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Ra[d]||(Ra[d]=e.value):Wa(d))}}
var I=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),J=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Ya=document.implementation.createHTMLDocument("inert");function Za(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var $a=["firstElementChild","lastElementChild","children","childElementCount"],ab=["querySelector","querySelectorAll"];
function bb(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?H(window.EventTarget.prototype,a):(H(Node.prototype,a),H(Window.prototype,a));Qa?H(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Xa(Node.prototype,{parentNode:{get:function(){I.currentNode=this;return I.parentNode()}},firstChild:{get:function(){I.currentNode=this;return I.firstChild()}},lastChild:{get:function(){I.currentNode=
this;return I.lastChild()}},previousSibling:{get:function(){I.currentNode=this;return I.previousSibling()}},nextSibling:{get:function(){I.currentNode=this;return I.nextSibling()}},childNodes:{get:function(){var b=[];I.currentNode=this;for(var c=I.firstChild();c;)b.push(c),c=I.nextSibling();return b}},parentElement:{get:function(){J.currentNode=this;return J.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Za(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});H(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
H(HTMLElement.prototype,["parentElement","contains"]);a={firstElementChild:{get:function(){J.currentNode=this;return J.firstChild()}},lastElementChild:{get:function(){J.currentNode=this;return J.lastChild()}},children:{get:function(){var b=[];J.currentNode=this;for(var c=J.firstChild();c;)b.push(c),c=J.nextSibling();return sa(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Qa?(H(Element.prototype,$a),H(Element.prototype,["previousElementSibling","nextElementSibling",
"innerHTML","className"]),H(HTMLElement.prototype,["children","innerHTML","className"])):(Xa(Element.prototype,a),Xa(Element.prototype,{previousElementSibling:{get:function(){J.currentNode=this;return J.previousSibling()}},nextElementSibling:{get:function(){J.currentNode=this;return J.nextSibling()}},innerHTML:{get:function(){return Pa(this,va)},set:function(b){var c="template"===this.localName?this.content:this;Za(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Ya.namespaceURI?
Ya.createElementNS(this.namespaceURI,d):Ya.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}},className:{get:function(){return this.getAttribute("class")||""},set:function(b){this.setAttribute("class",b)}}}));H(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));H(Element.prototype,ab);H(HTMLElement.prototype,["focus","blur"]);window.HTMLTemplateElement&&
H(window.HTMLTemplateElement.prototype,["innerHTML"]);Qa?H(DocumentFragment.prototype,$a):Xa(DocumentFragment.prototype,a);H(DocumentFragment.prototype,ab);Qa?(H(Document.prototype,$a),H(Document.prototype,["activeElement"])):Xa(Document.prototype,a);H(Document.prototype,["importNode","getElementById"]);H(Document.prototype,ab)};var cb=G({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get shadowRoot(){return this.__shady_shadowRoot}}),db=G({get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=
a},get innerHTML(){return this.__shady_innerHTML},set innerHTML(a){return this.__shady_innerHTML=a}}),eb=G({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}});function fb(a){for(var b in a){var c=a[b];c&&(c.enumerable=!1)}}fb(cb);fb(db);fb(eb);var gb=y.h||!0===y.l,hb=gb?function(){}:function(a){var b=u(a);b.Ya||(b.Ya=!0,ya(a,eb))},ib=gb?function(){}:function(a){var b=u(a);b.Xa||(b.Xa=!0,ya(a,cb),window.customElements&&window.customElements.polyfillWrapFlushCallback&&!y.l||ya(a,db))};var jb="__eventWrappers"+Date.now(),kb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),lb=function(){function a(){}var b=!1,c={get capture(){b=!0;return!1}};window.addEventListener("test",a,c);window.removeEventListener("test",a,c);return b}();function mb(a){if(a&&"object"===typeof a){var b=!!a.capture;var c=!!a.once;var d=!!a.passive;var e=a.D}else b=!!a,d=c=!1;return{Ra:e,capture:b,once:c,passive:d,Oa:lb?a:b}}
var nb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,
drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},ob={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};function pb(a){return a instanceof Node?a.__shady_getRootNode():a}
function qb(a,b){var c=[],d=a;for(a=pb(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function rb(a){a.__composedPath||(a.__composedPath=qb(a.target,!0));return a.__composedPath}function sb(a,b){if(!D)return a;a=qb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=pb(d),f!==e&&(g=a.indexOf(f),e=f),!D(f)||-1<g)return d}
function tb(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var ub={focus:!0,blur:!0};function vb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}function wb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!vb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function xb(a){var b=a.composedPath(),c=b.map(function(m){return sb(m,b)}),d=a.bubbles;Object.defineProperty(a,"currentTarget",{configurable:!0,enumerable:!0,get:function(){return g}});var e=Event.CAPTURING_PHASE;Object.defineProperty(a,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return e}});for(var f=b.length-1;0<=f;f--){var g=b[f];e=g===c[f]?Event.AT_TARGET:Event.CAPTURING_PHASE;wb(a,g,"capture");if(a.ca)return}for(f=0;f<b.length;f++){g=b[f];var k=g===c[f];if(k||d)if(e=k?Event.AT_TARGET:
Event.BUBBLING_PHASE,wb(a,g,"bubble"),a.ca)return}e=0;g=null}function yb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var k=a[g],m=k.type,p=k.capture,q=k.once,w=k.passive;if(b===k.node&&c===m&&d===p&&e===q&&f===w)return g}return-1}function zb(a){Da();return!y.N&&this instanceof Node&&!qa(document,this)?(a.__target||Ab(a,this),xb(a)):this.__shady_native_dispatchEvent(a)}
function Bb(a,b,c){var d=mb(c),e=d.capture,f=d.once,g=d.passive,k=d.Ra;d=d.Oa;if(b){var m=typeof b;if("function"===m||"object"===m)if("object"!==m||b.handleEvent&&"function"===typeof b.handleEvent){if(ob[a])return this.__shady_native_addEventListener(a,b,d);var p=k||this;if(k=b[jb]){if(-1<yb(k,p,a,e,f,g))return}else b[jb]=[];k=function(q){f&&this.__shady_removeEventListener(a,b,c);q.__target||Ab(q);if(p!==this){var w=Object.getOwnPropertyDescriptor(q,"currentTarget");Object.defineProperty(q,"currentTarget",
{get:function(){return p},configurable:!0});var B=Object.getOwnPropertyDescriptor(q,"eventPhase");Object.defineProperty(q,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return e?Event.CAPTURING_PHASE:Event.BUBBLING_PHASE}})}q.__previousCurrentTarget=q.currentTarget;if(!D(p)&&"slot"!==p.localName||-1!=q.composedPath().indexOf(p))if(q.composed||-1<q.composedPath().indexOf(p))if(vb(q)&&q.target===q.relatedTarget)q.eventPhase===Event.BUBBLING_PHASE&&q.stopImmediatePropagation();else if(q.eventPhase===
Event.CAPTURING_PHASE||q.bubbles||q.target===p||p instanceof Window){var Q="function"===m?b.call(p,q):b.handleEvent&&b.handleEvent(q);p!==this&&(w?(Object.defineProperty(q,"currentTarget",w),w=null):delete q.currentTarget,B?(Object.defineProperty(q,"eventPhase",B),B=null):delete q.eventPhase);return Q}};b[jb].push({node:p,type:a,capture:e,once:f,passive:g,pc:k});this.__handlers=this.__handlers||{};this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]};this.__handlers[a][e?"capture":"bubble"].push(k);
ub[a]||this.__shady_native_addEventListener(a,k,d)}}}
function Cb(a,b,c){if(b){var d=mb(c);c=d.capture;var e=d.once,f=d.passive,g=d.Ra;d=d.Oa;if(ob[a])return this.__shady_native_removeEventListener(a,b,d);var k=g||this;g=void 0;var m=null;try{m=b[jb]}catch(p){}m&&(e=yb(m,k,a,c,e,f),-1<e&&(g=m.splice(e,1)[0].pc,m.length||(b[jb]=void 0)));this.__shady_native_removeEventListener(a,g||b,d);g&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][c?"capture":"bubble"],b=a.indexOf(g),-1<b&&a.splice(b,1))}}
function Db(){for(var a in ub)window.__shady_native_addEventListener(a,function(b){b.__target||(Ab(b),xb(b))},!0)}
var Eb=G({get composed(){void 0===this.__composed&&(kb?this.__composed="focusin"===this.type||"focusout"===this.type||kb(this):!1!==this.isTrusted&&(this.__composed=nb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=qb(this.__target,this.composed));return this.__composedPath},get target(){return sb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=qb(this.__relatedTarget,!0));return sb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.ca=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.ca=this.__immediatePropagationStopped=!0}});
function Ab(a,b){b=void 0===b?a.target:b;a.__target=b;a.__relatedTarget=a.relatedTarget;if(y.h){b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;F(c,Eb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else F(a,Eb)}var Fb=tb(Event),Gb=tb(CustomEvent),Hb=tb(MouseEvent);
function Ib(){if(!kb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}
var Jb=Object.getOwnPropertyNames(Element.prototype).filter(function(a){return"on"===a.substring(0,2)}),Kb=Object.getOwnPropertyNames(HTMLElement.prototype).filter(function(a){return"on"===a.substring(0,2)});function Lb(a){return{set:function(b){var c=u(this),d=a.substring(2);c.C||(c.C={});c.C[a]&&this.removeEventListener(d,c.C[a]);this.__shady_addEventListener(d,b);c.C[a]=b},get:function(){var b=x(this);return b&&b.C&&b.C[a]},configurable:!0}};function Mb(a,b){return{index:a,O:[],X:b}}
function Nb(a,b,c,d){var e=0,f=0,g=0,k=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){k=a.length;for(var p=c.length,q=0;q<m-g&&Ob(a[--k],c[--p]);)q++;k=q}e+=g;f+=g;b-=k;d-=k;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Mb(e,0);f<d;)b.O.push(c[f++]);return[b]}if(f==d)return[Mb(e,b-e)];m=e;g=f;d=d-g+1;k=b-m+1;b=Array(d);for(p=0;p<d;p++)b[p]=Array(k),b[p][0]=p;for(p=0;p<k;p++)b[0][p]=p;for(p=1;p<d;p++)for(q=1;q<k;q++)if(a[m+q-1]===c[g+p-1])b[p][q]=
b[p-1][q-1];else{var w=b[p-1][q]+1,B=b[p][q-1]+1;b[p][q]=w<B?w:B}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)0==m?(a.push(2),g--):0==g?(a.push(3),m--):(k=b[m-1][g-1],p=b[m-1][g],q=b[m][g-1],w=p<q?p<k?p:k:q<k?q:k,w==k?(k==d?a.push(0):(a.push(1),d=k),m--,g--):w==p?(a.push(3),m--,d=p):(a.push(2),g--,d=q));a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Mb(e,0));b.X++;e++;b.O.push(c[f]);f++;break;case 2:b||(b=Mb(e,0));
b.X++;e++;break;case 3:b||(b=Mb(e,0)),b.O.push(c[f]),f++}b&&m.push(b);return m}function Ob(a,b){return a===b};var Pb=G({dispatchEvent:zb,addEventListener:Bb,removeEventListener:Cb});var Qb=null;function K(){Qb||(Qb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Qb||null}function Rb(a,b,c){var d=K();return d&&"class"===b?(d.setElementClass(a,c),!0):!1}function Tb(a,b){var c=K();c&&c.unscopeNode(a,b)}function Ub(a,b){var c=K();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)c=c&&Ub(a,b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}
function Vb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=K();return b?b.currentScopeForNode(a):""}function Wb(a,b){if(a)for(a.nodeType===Node.ELEMENT_NODE&&b(a),a=a.__shady_firstChild;a;a=a.__shady_nextSibling)a.nodeType===Node.ELEMENT_NODE&&Wb(a,b)};var Xb=window.document,Yb=y.N,Zb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),$b=Zb&&Zb.get;function ac(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function bc(a){var b=x(a);if(b&&void 0!==b.aa)for(b=a.__shady_firstChild;b;b=b.__shady_nextSibling)bc(b);if(a=x(a))a.aa=void 0}function cc(a){var b=a;if(a&&"slot"===a.localName){var c=x(a);(c=c&&c.I)&&(b=c.length?c[0]:cc(a.__shady_nextSibling))}return b}
function dc(a,b,c){if(a=(a=x(a))&&a.M){if(b)if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(var d=0,e=b.childNodes.length;d<e;d++)a.addedNodes.push(b.childNodes[d]);else a.addedNodes.push(b);c&&a.removedNodes.push(c);Fa(a)}}
var gc=G({get parentNode(){var a=x(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=x(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=x(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=x(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=x(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(C(this)){var a=x(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=x(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if($b&&$b.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(null===a||qa(a,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(D(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(C(this)){for(var a=[],b=this.__shady_firstChild;b;b=b.__shady_nextSibling)b.nodeType!==Node.COMMENT_NODE&&a.push(b.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!C(this)&&
y.h){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&ac(this);this.__shady_native_textContent=a}else ac(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Xb&&a.ownerDocument!==Xb)return this.__shady_native_insertBefore(a,b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");
if(b){var c=x(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;dc(this,a);var d=[],e=(c=M(this))?c.host.localName:Vb(this),f=a.__shady_parentNode;if(f){var g=Vb(a);var k=!!c||!M(a)||Yb&&void 0!==this.__noInsertionPoint;f.__shady_removeChild(a,k)}f=!0;var m=(!Yb||void 0===a.__noInsertionPoint&&void 0===
this.__noInsertionPoint)&&!Ub(a,e),p=c&&!a.__noInsertionPoint&&(!Yb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(p||m)m&&(g=g||Vb(a)),Wb(a,function(q){p&&"slot"===q.localName&&d.push(q);if(m){var w=g;K()&&(w&&Tb(q,w),(w=K())&&w.scopeNode(q,e))}});d.length&&(c.ua(d),c.j());C(this)&&(ec(a,this,b),k=x(this),k.root?(f=!1,ja(this)&&k.root.j()):c&&"slot"===this.localName&&(f=!1,c.j()));f?(c=D(this)?this.host:this,b?(b=cc(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==
this.ownerDocument&&this.ownerDocument.adoptNode(a);return a},appendChild:function(a){if(this!=a||!D(a))return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Xb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);dc(this,null,a);var c=M(a),d=c&&c.Cb(a),e=x(this);if(C(this)&&(fc(a,this),ja(this))){e.root.j();var f=!0}if(K()&&!b&&c&&a.nodeType!==Node.TEXT_NODE){var g=
Vb(a);Wb(a,function(k){Tb(k,g)})}bc(a);c&&((b="slot"===this.localName)&&(f=!0),(d||b)&&c.j());f||(f=D(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=
this.__shady_firstChild;for(var c;a;a=a.__shady_nextSibling)c=a.__shady_cloneNode(!0),b.__shady_appendChild(c)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=u(this),c=b.aa;void 0===c&&(D(this)?(c=this,b.aa=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.aa=c)));return c}},contains:function(a){return ra(this,a)}});var hc=G({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&a.T();return(a=x(this))&&a.assignedSlot||null}});function ic(a,b,c){var d=[];jc(a,b,c,d);return d}function jc(a,b,c,d){for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling){var e;if(e=a.nodeType===Node.ELEMENT_NODE){e=a;var f=b,g=c,k=d,m=f(e);m&&k.push(e);g&&g(m)?e=m:(jc(e,f,g,k),e=void 0)}if(e)break}}
var N=G({get firstElementChild(){var a=x(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=x(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return C(this)?sa(Array.prototype.filter.call(wa(this),
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),kc=G({querySelector:function(a){return ic(this,function(b){return la.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return sa(b.filter(function(d){return d.__shady_getRootNode()==c}))}return sa(ic(this,function(d){return la.call(d,
a)}))}}),lc=y.N&&!y.l?za({},N):N;za(N,kc);var mc=window.document;function nc(a,b){"slot"===b?(a=a.__shady_parentNode,ja(a)&&x(a).root.j()):"slot"===a.localName&&"name"===b&&(b=M(a))&&(b.Pb(a),b.j())}
var oc=G({get previousElementSibling(){var a=x(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=x(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){this.ownerDocument!==mc?this.__shady_native_setAttribute(a,b):Rb(this,a,b)||(this.__shady_native_setAttribute(a,b),nc(this,a))},removeAttribute:function(a){this.ownerDocument!==mc?this.__shady_native_removeAttribute(a):Rb(this,a,"")?""===this.getAttribute(a)&&this.__shady_native_removeAttribute(a):(this.__shady_native_removeAttribute(a),
nc(this,a))}});y.N||Jb.forEach(function(a){oc[a]=Lb(a)});
var sc=G({attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");if(a.shadyUpgradeFragment&&!y.Va){var b=a.shadyUpgradeFragment;b.__proto__=ShadowRoot.prototype;b.Aa(this,a);pc(b,b);a=b.__noInsertionPoint?null:b.querySelectorAll("slot");b.__noInsertionPoint=void 0;a&&a.length&&(b.ua(a),b.j());b.host.__shady_native_appendChild(b)}else b=new qc(rc,this,a);return this.__CE_shadowRoot=b},get shadowRoot(){var a=x(this);return a&&a.ec||null}});
za(oc,sc);var tc=document.implementation.createHTMLDocument("inert"),uc=G({get innerHTML(){return C(this)?Pa("template"===this.localName?this.content:this,wa):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{ac(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==tc.namespaceURI?tc.createElementNS(this.namespaceURI,b):tc.createElement(b);for(y.h?b.__shady_native_innerHTML=a:b.innerHTML=a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var vc=G({blur:function(){var a=x(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});y.N||Kb.forEach(function(a){vc[a]=Lb(a)});var wc=G({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&D(b)&&b.T();return(b=x(this))?(a&&a.flatten?b.I:b.assignedNodes)||[]:[]}},addEventListener:function(a,b,c){if("slot"!==this.localName||"slotchange"===a)Bb.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.D=this;d.__shady_addEventListener(a,b,c)}},removeEventListener:function(a,
b,c){if("slot"!==this.localName||"slotchange"===a)Cb.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.D=this;d.__shady_removeEventListener(a,b,c)}}});var xc=G({getElementById:function(a){return""===a?null:ic(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var yc=G({get activeElement(){var a=y.h?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!D(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=M(a);b&&b!==this;)a=b.host,b=M(a);return this===document?b?null:a:b===this?a:null}});var zc=window.document,Ac=G({importNode:function(a,b){if(a.ownerDocument!==zc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b)for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b=this.__shady_importNode(a,!0),c.__shady_appendChild(b);return c}});var Bc=G({dispatchEvent:zb,addEventListener:Bb.bind(window),removeEventListener:Cb.bind(window)});var Cc={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(Cc.parentElement=gc.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(Cc.contains=gc.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(Cc.children=N.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(Cc.innerHTML=uc.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(Cc.className=oc.className);
var O={EventTarget:[Pb],Node:[gc,window.EventTarget?null:Pb],Text:[hc],Comment:[hc],CDATASection:[hc],ProcessingInstruction:[hc],Element:[oc,N,hc,!y.h||"innerHTML"in Element.prototype?uc:null,window.HTMLSlotElement?null:wc],HTMLElement:[vc,Cc],HTMLSlotElement:[wc],DocumentFragment:[lc,xc],Document:[Ac,lc,xc,yc],Window:[Bc]},Dc=y.h?null:["innerHTML","textContent"];function P(a,b,c,d){b.forEach(function(e){return a&&e&&F(a,e,c,d)})}
function Ec(a){var b=a?null:Dc,c;for(c in O)P(window[c]&&window[c].prototype,O[c],a,b)}["Text","Comment","CDATASection","ProcessingInstruction"].forEach(function(a){var b=window[a],c=Object.create(b.prototype);c.__shady_protoIsPatched=!0;P(c,O.EventTarget);P(c,O.Node);O[a]&&P(c,O[a]);b.prototype.__shady_patchedProto=c});function Fc(a){a.__shady_protoIsPatched=!0;P(a,O.EventTarget);P(a,O.Node);P(a,O.Element);P(a,O.HTMLElement);P(a,O.HTMLSlotElement);return a};var Gc=y.pa,Hc=y.h;function Ic(a,b){if(Gc&&!a.__shady_protoIsPatched&&!D(a)){var c=Object.getPrototypeOf(a),d=c.hasOwnProperty("__shady_patchedProto")&&c.__shady_patchedProto;d||(d=Object.create(c),Fc(d),c.__shady_patchedProto=d);Object.setPrototypeOf(a,d)}Hc||(1===b?hb(a):2===b&&ib(a))}
function Jc(a,b,c,d){Ic(a,1);d=d||null;var e=u(a),f=d?u(d):null;e.previousSibling=d?f.previousSibling:b.__shady_lastChild;if(f=x(e.previousSibling))f.nextSibling=a;if(f=x(e.nextSibling=d))f.previousSibling=a;e.parentNode=b;d?d===c.firstChild&&(c.firstChild=a):(c.lastChild=a,c.firstChild||(c.firstChild=a));c.childNodes=null}
function ec(a,b,c){Ic(b,2);var d=u(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)Jc(a,b,d,c);else Jc(a,b,d,c)}
function fc(a,b){var c=u(a);b=u(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(u(a).nextSibling=d);d&&(u(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function pc(a,b){var c=u(a);if(b||void 0===c.firstChild){c.childNodes=null;var d=c.firstChild=a.__shady_native_firstChild;c.lastChild=a.__shady_native_lastChild;Ic(a,2);c=d;for(d=void 0;c;c=c.__shady_native_nextSibling){var e=u(c);e.parentNode=b||a;e.nextSibling=c.__shady_native_nextSibling;e.previousSibling=d||null;d=c;Ic(c,1)}}};var Kc=G({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.D=c.D||this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.D=c.D||this;this.host.__shady_removeEventListener(a,b,c)}});function Lc(a,b){F(a,Kc,b);F(a,yc,b);F(a,uc,b);F(a,N,b);y.l&&!b?(F(a,gc,b),F(a,xc,b)):y.h||(F(a,eb),F(a,cb),F(a,db))};var rc={},R=y.deferConnectionCallbacks&&"loading"===document.readyState,Mc;function Nc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}function qc(a,b,c){if(a!==rc)throw new TypeError("Illegal constructor");this.a=null;this.Aa(b,c)}l=qc.prototype;
l.Aa=function(a,b){this.host=a;this.mode=b&&b.mode;pc(this.host);a=u(this.host);a.root=this;a.ec="closed"!==this.mode?this:null;a=u(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;if(y.preferPerformance)for(;a=this.host.__shady_native_firstChild;)this.host.__shady_native_removeChild(a);else this.j()};l.j=function(){var a=this;this.G||(this.G=!0,Ca(function(){return a.T()}))};l.rb=function(){for(var a,b=this;b;)b.G&&(a=b),b=b.qb();return a};
l.qb=function(){var a=this.host.__shady_getRootNode();if(D(a)){var b=x(this.host);if(b&&0<b.S)return a}};l.T=function(){var a=this.G&&this.rb();a&&a._renderSelf()};l.mb=function(){!this.za&&this.G&&this.T()};
l._renderSelf=function(){var a=R;R=!0;this.G=!1;this.a&&(this.hb(),this.fb());if(!y.preferPerformance&&!this.za)for(var b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling){var c=x(b);b.__shady_native_parentNode!==this.host||"slot"!==b.localName&&c.assignedSlot||this.host.__shady_native_removeChild(b)}this.za=!0;R=a;Mc&&Mc()};
l.hb=function(){this.W();for(var a=0,b;a<this.a.length;a++)b=this.a[a],this.eb(b);for(a=this.host.__shady_firstChild;a;a=a.__shady_nextSibling)this.wa(a);for(a=0;a<this.a.length;a++){b=this.a[a];var c=x(b);if(!c.assignedNodes.length)for(var d=b.__shady_firstChild;d;d=d.__shady_nextSibling)this.wa(d,b);(d=(d=x(b.__shady_parentNode))&&d.root)&&(d.ya()||d.G)&&d._renderSelf();this.ta(c.I,c.assignedNodes);if(d=c.Ea){for(var e=0;e<d.length;e++)x(d[e]).ha=null;c.Ea=null;d.length>c.assignedNodes.length&&
(c.la=!0)}c.la&&(c.la=!1,this.xa(b))}};l.wa=function(a,b){var c=u(a),d=c.ha;c.ha=null;b||(b=(b=this.c[a.__shady_slot||"__catchall"])&&b[0]);b?(u(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;d!==c.assignedSlot&&c.assignedSlot&&(u(c.assignedSlot).la=!0)};l.eb=function(a){var b=x(a),c=b.assignedNodes;b.assignedNodes=[];b.I=[];if(b.Ea=c)for(b=0;b<c.length;b++){var d=x(c[b]);d.ha=d.assignedSlot;d.assignedSlot===a&&(d.assignedSlot=null)}};
l.ta=function(a,b){for(var c=0,d=void 0;c<b.length&&(d=b[c]);c++)if("slot"==d.localName){var e=x(d).assignedNodes;e&&e.length&&this.ta(a,e)}else a.push(b[c])};l.xa=function(a){a.__shady_native_dispatchEvent(new Event("slotchange"));a=x(a);a.assignedSlot&&this.xa(a.assignedSlot)};l.fb=function(){for(var a=this.a,b=[],c=0;c<a.length;c++){var d=a[c].__shady_parentNode,e=x(d);e&&e.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.Ob(c===this?this.host:c,this.gb(c))};
l.gb=function(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)if(this.tb(a))for(var c=x(a).I,d=0;d<c.length;d++)b.push(c[d]);else b.push(a);return b};l.tb=function(a){return"slot"==a.localName};
l.Ob=function(a,b){for(var c=va(a),d=Nb(b,b.length,c,c.length),e=0,f=0,g=void 0;e<d.length&&(g=d[e]);e++){for(var k=0,m=void 0;k<g.O.length&&(m=g.O[k]);k++)m.__shady_native_parentNode===a&&a.__shady_native_removeChild(m),c.splice(g.index+f,1);f-=g.X}e=0;for(f=void 0;e<d.length&&(f=d[e]);e++)for(g=c[f.index],k=f.index;k<f.index+f.X;k++)m=b[k],a.__shady_native_insertBefore(m,g),c.splice(k,0,m)};l.lb=function(){this.A=this.A||[];this.a=this.a||[];this.c=this.c||{}};
l.ua=function(a){this.lb();this.A.push.apply(this.A,a instanceof Array?a:ca(ba(a)))};l.W=function(){this.A&&this.A.length&&(this.wb(this.A),this.A=[])};l.wb=function(a){for(var b,c=0;c<a.length;c++){var d=a[c];pc(d);var e=d.__shady_parentNode;pc(e);e=x(e);e.S=(e.S||0)+1;e=this.Ca(d);this.c[e]?(b=b||{},b[e]=!0,this.c[e].push(d)):this.c[e]=[d];this.a.push(d)}if(b)for(var f in b)this.c[f]=this.Ga(this.c[f])};l.Ca=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.Za=b};
l.Ga=function(a){return a.sort(function(b,c){b=Nc(b);for(var d=Nc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=wa(c.__shady_parentNode),b.indexOf(c)-b.indexOf(f)}})};l.Cb=function(a){if(this.a){this.W();var b=this.c,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e];if(ra(a,f)){d.splice(e,1);var g=this.a.indexOf(f);0<=g&&(this.a.splice(g,1),(g=x(f.__shady_parentNode))&&g.S&&g.S--);e--;this.Db(f);g=!0}}return g}};
l.Pb=function(a){if(this.a){this.W();var b=a.Za,c=this.Ca(a);if(c!==b){b=this.c[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.c[c]||(this.c[c]=[]);b.push(a);1<b.length&&(this.c[c]=this.Ga(b))}}};l.Db=function(a){a=x(a);var b=a.I;if(b)for(var c=0;c<b.length;c++){var d=b[c],e=d.__shady_native_parentNode;e&&e.__shady_native_removeChild(d)}a.I=[];a.assignedNodes=[]};l.ya=function(){this.W();return!(!this.a||!this.a.length)};
(function(a){a.__proto__=DocumentFragment.prototype;Lc(a,"__shady_");Lc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(qc.prototype);
if(window.customElements&&window.customElements.define&&y.na&&!y.preferPerformance){var Oc=new Map;Mc=function(){var a=[];Oc.forEach(function(d,e){a.push([e,d])});Oc.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.__shadydom_connectedCallback():c.__shadydom_disconnectedCallback()}};R&&document.addEventListener("readystatechange",function(){R=!1;Mc()},{once:!0});var Pc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.__shadydom_connectedCallback=
function(){R?Oc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.__shadydom_disconnectedCallback=function(){R?this.isConnected||Oc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Qc=window.customElements.define,Rc=function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Qc.call(window.customElements,a,Pc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d};window.customElements.define=
Rc;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:Rc,configurable:!0})}function M(a){a=a.__shady_getRootNode();if(D(a))return a};function Sc(a){this.node=a}l=Sc.prototype;l.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};l.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};l.appendChild=function(a){return this.node.__shady_appendChild(a)};l.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};l.removeChild=function(a){return this.node.__shady_removeChild(a)};l.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
l.cloneNode=function(a){return this.node.__shady_cloneNode(a)};l.getRootNode=function(a){return this.node.__shady_getRootNode(a)};l.contains=function(a){return this.node.__shady_contains(a)};l.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};l.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};l.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};l.hasAttribute=function(a){return this.node.__shady_native_hasAttribute(a)};l.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};
l.attachShadow=function(a){return this.node.__shady_attachShadow(a)};l.focus=function(){this.node.__shady_native_focus()};l.blur=function(){this.node.__shady_blur()};l.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};l.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};l.querySelector=function(a){return this.node.__shady_querySelector(a)};
l.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};l.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
ea.Object.defineProperties(Sc.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(D(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(D(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}},className:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_className},set:function(a){return this.node.__shady_className=
a}}});function Tc(a){Object.defineProperty(Sc.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})}Jb.forEach(function(a){return Tc(a)});Kb.forEach(function(a){return Tc(a)});var Uc=new WeakMap;function Vc(a){if(D(a)||a instanceof Sc)return a;var b=Uc.get(a);b||(b=new Sc(a),Uc.set(a,b));return b};if(y.na){var Wc=y.h?function(a){return a}:function(a){ib(a);hb(a);return a},ShadyDOM={inUse:y.na,patch:Wc,isShadyRoot:D,enqueue:Ca,flush:Da,flushInitial:function(a){a.mb()},settings:y,filterMutations:Ia,observeChildren:Ga,unobserveChildren:Ha,deferConnectionCallbacks:y.deferConnectionCallbacks,preferPerformance:y.preferPerformance,handlesDynamicScoping:!0,wrap:y.l?Vc:Wc,wrapIfNeeded:!0===y.l?Vc:function(a){return a},Wrapper:Sc,composedPath:rb,noPatch:y.l,patchOnDemand:y.pa,nativeMethods:Ra,nativeTree:Sa,
patchElementProto:Fc};window.ShadyDOM=ShadyDOM;bb();Ec("__shady_");Object.defineProperty(document,"_activeElement",yc.activeElement);F(Window.prototype,Bc,"__shady_");y.l?y.pa&&F(Element.prototype,sc):(Ec(),Ib());Db();window.Event=Fb;window.CustomEvent=Gb;window.MouseEvent=Hb;window.ShadowRoot=qc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Xc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Yc(a){var b=a=a.replace(Zc,"").replace($c,""),c=new Xc;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,k=g.rules[g.rules.length-1]||null;d=new Xc;d.start=e+1;d.parent=g;d.previous=k;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return ad(c,a)}
function ad(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(bd," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=4:c.match(cd)&&(a.type=7,a.keyframesName=a.selector.split(bd).pop()):a.type=0===c.indexOf("--")?
1E3:1);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)ad(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function dd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(e))for(var f=0,g=e.length,k=void 0;f<g&&(k=e[f]);f++)d=dd(k,b,d);else b?b=a.cssText:(b=a.cssText,b=b.replace(ed,"").replace(fd,""),b=b.replace(gd,"").replace(hd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&0===a.selector.indexOf("--")}var Zc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,$c=/@import[^;]*;/gim,ed=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,fd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,gd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,hd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,cd=/^@[^\s]*keyframes/,bd=/\s+/g;var S=!(window.ShadyDOM&&window.ShadyDOM.inUse),id;function jd(a){id=a&&a.shimcssproperties?!1:S||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var kd;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(kd=window.ShadyCSS.cssBuild);var ld=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?id=window.ShadyCSS.nativeCss:window.ShadyCSS?(jd(window.ShadyCSS),window.ShadyCSS=void 0):jd(window.WebComponents&&window.WebComponents.flags);var T=id;var md=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,nd=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,od=/(--[\w-]+)\s*([:,;)]|$)/gi,pd=/(animation\s*:)|(animation-name\s*:)/,qd=/@media\s(.*)/,rd=/\{[^}]*\}/g;var sd=new Set;function td(a,b){if(!a)return"";"string"===typeof a&&(a=Yc(a));b&&ud(a,b);return dd(a,T)}function vd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Yc(a.textContent));return a.__cssRules||null}function wd(a){return!!a.parent&&7===a.parent.type}function ud(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&4===f){var g=a.selector.match(qd);g&&(window.matchMedia(g[1]).matches||(e=!0))}1===f?b(a):c&&7===f?c(a):1E3===f&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)ud(g,b,c,d)}}
function xd(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;yd(e,c,d);return e}var U=null;function zd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(U?U.nextSibling:null)||b.firstChild);return U=a}function yd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}
function Ad(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function Bd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Ad(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=Bd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Gd(a,b){S?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var Hd=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function V(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,P:c}}function Id(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Ad(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Jd(a){if(void 0!==kd)return kd;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Kd(a){a=void 0===a?"":a;return""!==a&&T?S?"shadow"===a:"shady"===a:!1};function Ld(){}function Md(a,b){var c=W;c.V(a,function(d){c.element(d,b||"")})}l=Ld.prototype;l.V=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a="template"===a.localName?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.V(a[c],b)};
l.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Gd(a,b)):Gd(a,(d?d+" ":"")+"style-scope "+b)}};function Nd(a,b,c){var d=W;d.V(a,function(e){d.element(e,b,!0);d.element(e,c)})}function Od(a,b){var c=W;c.V(a,function(d){c.element(d,b||"",!0)})}
function Pd(a,b,c,d,e){var f=W;e=void 0===e?"":e;""===e&&(S||"shady"===(void 0===d?"":d)?e=td(b,c):(a=V(a),e=Qd(f,b,a.is,a.P,c)+"\n\n"));return e.trim()}function Qd(a,b,c,d,e){var f=a.ea(c,d);c=a.va(c);return td(b,function(g){g.ac||(a.Ha(g,a.ja,c,f),g.ac=!0);e&&e(g,c,f)})}l.va=function(a){return a?"."+a:""};l.ea=function(a,b){return b?"[is="+a+"]":a};l.Ha=function(a,b,c,d){a.selector=a.i=this.Ia(a,b,c,d)};
l.Ia=function(a,b,c,d){var e=Id(a.selector);if(!wd(a)){a=0;for(var f=e.length,g=void 0;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.filter(function(k){return!!k}).join(",")};l.Ka=function(a){return a.replace(Rd,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};
l.Bb=function(a){for(var b=[],c;c=a.match(Sd);){var d=c.index,e=Ad(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{qa:a,matches:b}};l.Fb=function(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])};
l.ja=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Rd.test(a);f&&(a=a.replace(Rd,function(m,p,q){return":"+p+"("+q.replace(/\s/g,"")+")"}),a=this.Ka(a));var g=Sd.test(a);if(g){var k=this.Bb(a);a=k.qa;k=k.matches}a=a.replace(Td,":host $1");a=a.replace(Ud,function(m,p,q){e||(m=d.Lb(q,p,b,c),e=e||m.stop,p=m.Sb,q=m.value);return p+q});g&&(a=this.Fb(a,k));f&&(a=this.Ka(a));return a=a.replace(Vd,function(m,p,q,w){return'[dir="'+q+'"] '+p+w+", "+p+'[dir="'+q+'"]'+w})};
l.Lb=function(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=this.Nb(a,d):0!==e&&(a=c?this.Ja(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Wd,function(g,k){return" > "+k}))}return{value:a,Sb:b,stop:f}};l.Ja=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")};
l.Nb=function(a,b){var c=a.match(Xd);return(c=c&&c[2].trim()||"")?c[0].match(Yd)?a.replace(Xd,function(d,e,f){return b+f}):c.split(Yd)[0]===b?c:"should_not_match":a.replace(":host",b)};function Zd(a){":root"===a.selector&&(a.selector="html")}l.Mb=function(a){return a.match(":host")?"":a.match("::slotted")?this.ja(a,":not(.style-scope)"):this.Ja(a.trim(),":not(.style-scope)")};ea.Object.defineProperties(Ld.prototype,{R:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Rd=/:(nth[-\w]+)\(([^)]+)\)/,Ud=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Yd=/[[.:#*]/,Td=/^(::slotted)/,Xd=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Wd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Vd=/(.*):dir\((?:(ltr|rtl))\)(.*)/,Sd=/:(?:matches|any|-(?:webkit|moz)-any)/,W=new Ld;function $d(a,b,c,d,e){this.o=a||null;this.placeholder=b||null;this.oa=c||[];this.J=null;this.cssBuild=e||"";this.P=d||"";this.H=this.m=this.v=null}function X(a){return a?a.__styleInfo:null}function ae(a,b){return a.__styleInfo=b}$d.prototype.sb=function(){return this.o};$d.prototype._getStyleRules=$d.prototype.sb;function be(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ce=/:host\s*>\s*/,de=navigator.userAgent.match("Trident");function ee(){}function fe(a){var b={},c=[],d=0;ud(a,function(f){ge(f);f.index=d++;f=f.f.cssText;for(var g;g=od.exec(f);){var k=g[1];":"!==g[2]&&(b[k]=!0)}},function(f){c.push(f)});a.ub=c;a=[];for(var e in b)a.push(e);return a}
function ge(a){if(!a.f){var b={},c={};he(a,c)&&(b.u=c,a.rules=null);b.cssText=a.parsedCssText.replace(rd,"").replace(md,"");a.f=b}}function he(a,b){var c=a.f;if(c){if(c.u)return Object.assign(b,c.u),!0}else{c=a.parsedCssText;for(var d;a=md.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function ie(a,b,c){b&&(b=0<=b.indexOf(";")?je(a,b,c):Bd(b,function(d,e,f,g){if(!e)return d+g;(e=ie(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=ie(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function je(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){nd.lastIndex=0;if(f=nd.exec(e))e=ie(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=ie(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function ke(a,b){var c={},d=[];ud(a,function(e){e.f||ge(e);var f=e.i||e.parsedSelector;b&&e.f.u&&f&&be.call(b,f)&&(he(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{u:c,key:d}}
function le(a,b,c,d){b.f||ge(b);if(b.f.u){var e=V(a);a=e.is;e=e.P;e=a?W.ea(a,e):"html";var f=b.parsedSelector;var g=!!f.match(ce)||"html"===e&&-1<f.indexOf("html");var k=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),k=!g&&0===f.indexOf(e));if(g||k)c=e,k&&(b.i||(b.i=W.Ia(b,W.ja,W.va(a),e)),c=b.i||e),g&&"html"===e&&(c=b.i||b.rc),d({qa:c,$b:k,qc:g})}}
function me(a,b,c){var d={},e={};ud(b,function(f){le(a,f,c,function(g){be.call(a._element||a,g.qa)&&(g.$b?he(f,d):he(f,e))})},null,!0);return{fc:e,Zb:d}}
function ne(a,b,c,d){var e=V(b),f=W.ea(e.is,e.P),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),k=X(b);e=k.o;k=k.cssBuild;var m=a.ib(b,e,d);return Pd(b,e,function(p){var q="";p.f||ge(p);p.f.cssText&&(q=je(a,p.f.cssText,c));p.cssText=q;if(!S&&!wd(p)&&p.cssText){var w=q=p.cssText;null==p.Ma&&(p.Ma=pd.test(q));if(p.Ma)if(null==p.Z){p.Z=[];for(var B in m)w=m[B],w=w(q),q!==w&&(q=w,p.Z.push(B))}else{for(B=0;B<p.Z.length;++B)w=m[p.Z[B]],q=w(q);w=q}p.cssText=w;a.Jb(p,
g,f,d)}},k)}ee.prototype.ib=function(a,b,c){a=b.ub;b={};if(!S&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.Ib(e,c),b[e.keyframesName]=this.vb(e);return b};ee.prototype.vb=function(a){return function(b){return b.replace(a.bc,a.Ua)}};ee.prototype.Ib=function(a,b){a.bc=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.Ua=a.keyframesName+"-"+b;a.i=a.i||a.selector;a.selector=a.i.replace(a.keyframesName,a.Ua)};
ee.prototype.Jb=function(a,b,c,d){a.i=a.i||a.selector;d="."+d;for(var e=Id(a.i),f=0,g=e.length,k=void 0;f<g&&(k=e[f]);f++)e[f]=k.match(b)?k.replace(c,d):d+" "+k;a.selector=e.join(",")};function oe(a,b){var c=pe,d=vd(a);a.textContent=td(d,function(e){var f=e.cssText=e.parsedCssText;e.f&&e.f.cssText&&(f=f.replace(ed,"").replace(fd,""),e.cssText=je(c,f,b))})}ea.Object.defineProperties(ee.prototype,{Wa:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var pe=new ee;var qe={},re=window.customElements;if(re&&!S&&!ld){var se=re.define;re.define=function(a,b,c){qe[a]||(qe[a]=zd(a));se.call(re,a,b,c)}};function te(){this.cache={};this.mc=100}te.prototype.Qb=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.u[e]!==b[e])return!1}return!0};te.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({u:b,styleElement:c,m:d});e.length>this.mc&&e.shift();this.cache[a]=e};te.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.Qb(e,b,c))return e}};function ue(){}var ve=new RegExp(W.R+"\\s*([^\\s]*)");function we(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(ve))?a[1]:""}function xe(a){var b=Hd(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?V(a).is:""}
function ye(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=we(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Jd(e)))Od(e,g);else if(f instanceof ShadowRoot)for(f=xe(e),f!==g&&Nd(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.R+")"),g=0;g<e.length;g++){f=e[g];
var k=xe(f);k&&W.element(f,k)}}}}}
if(!(S||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var ze=new MutationObserver(ye),Ae=function(a){ze.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Ae(document);else{var Be=function(){Ae(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Be):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Be();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Be()})}ue=function(){ye(ze.takeRecords())}};var Ce={};var De=Promise.resolve();function Ee(a){if(a=Ce[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Fe(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ge(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,De.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var He={},Ie=new te;function Y(){this.Fa={};this.F=document.documentElement;var a=new Xc;a.rules=[];this.s=ae(this.F,new $d(a));this.fa=!1;this.b=this.g=null}l=Y.prototype;l.flush=function(){ue()};l.ob=function(a){var b=this.Fa[a]=(this.Fa[a]||0)+1;return a+"-"+b};l.Wb=function(a){return vd(a)};l.lc=function(a){return td(a)};
l.nb=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var d=a[c];if(d.hasAttribute("shady-unscoped")){if(!S){var e=d.textContent;if(!sd.has(e)){sd.add(e);var f=document.createElement("style");f.setAttribute("shady-unscoped","");f.textContent=e;document.head.appendChild(f)}d.parentNode.removeChild(d)}}else b.push(d.textContent),d.parentNode.removeChild(d)}return b.join("").trim()};
l.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
l.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!ld){S||qe[b]||(qe[b]=zd(b));a._prepared=!0;a.name=b;a.extends=c;Ce[b]=a;var d=Jd(a),e=Kd(d);c={is:b,extends:c};var f=this.nb(a)+(He[b]||"");this.K();if(!e){var g;if(g=!d)g=nd.test(f)||md.test(f),nd.lastIndex=0,md.lastIndex=0;var k=Yc(f);g&&T&&this.g&&this.g.transformRules(k,b);a._styleAst=k}g=[];T||(g=fe(a._styleAst));if(!g.length||T)b=this.pb(c,a._styleAst,S?a.content:null,qe[b]||null,d,e?f:""),a._style=b;a.Ab=g}};
l.dc=function(a,b){He[b]=a.join(" ")};l.prepareTemplateDom=function(a,b){if(!ld){var c=Jd(a);S||"shady"===c||a._domPrepared||(a._domPrepared=!0,Md(a.content,b))}};l.pb=function(a,b,c,d,e,f){f=Pd(a,b,null,e,f);return f.length?xd(f,a.is,c,d):null};l.Da=function(a){var b=V(a),c=b.is;b=b.P;var d=qe[c]||null,e=Ce[c];if(e){c=e._styleAst;var f=e.Ab;e=Jd(e);b=new $d(c,d,f,b,e);ae(a,b);return b}};
l.jb=function(){return!this.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim?(this.g=window.ShadyCSS.ApplyShim,this.g.invalidCallback=Ee,!0):!1};l.kb=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.Ta(b)},this.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.fa)&&a.flushCustomStyles()})})};l.K=function(){var a=this.jb();this.kb();return a};
l.flushCustomStyles=function(){if(!ld){var a=this.K();if(this.b){var b=this.b.processStyles();!a&&!this.b.enqueued||Kd(this.s.cssBuild)||(T?this.s.cssBuild||this.Hb(b):(this.Eb(b),this.ka(this.F,this.s),this.ab(b),this.fa&&this.styleDocument()),this.b.enqueued=!1)}}};
l.Eb=function(a){var b=this;a=a.map(function(c){return b.b.getStyleForCustomStyle(c)}).filter(function(c){return!!c});a.sort(function(c,d){c=d.compareDocumentPosition(c);return c&Node.DOCUMENT_POSITION_FOLLOWING?1:c&Node.DOCUMENT_POSITION_PRECEDING?-1:0});this.s.o.rules=a.map(function(c){return vd(c)})};
l.styleElement=function(a,b){if(ld){if(b){X(a)||ae(a,new $d(null));var c=X(a);this.Ba(c,b);Je(this,a,c)}}else if(c=X(a)||this.Da(a))this.ga(a)||(this.fa=!0),b&&this.Ba(c,b),T?Je(this,a,c):(this.flush(),this.ka(a,c),c.oa&&c.oa.length&&this.bb(a,c))};l.Ba=function(a,b){a.J=a.J||{};Object.assign(a.J,b)};
function Je(a,b,c){var d=V(b).is;if(c.J){var e=c.J,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}if(((e=Ce[d])||a.ga(b))&&(!e||""===Jd(e))&&e&&e._style&&!Fe(e)){if(Fe(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)a.K(),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=Pd(b,c.o),Ge(e);S&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=Pd(b,c.o));c.o=e._styleAst}}
l.ia=function(a){return(a=Hd(a).getRootNode().host)?X(a)||this.Da(a)?a:this.ia(a):this.F};l.ga=function(a){return a===this.F};
l.bb=function(a,b){var c=V(a).is,d=Ie.fetch(c,b.v,b.oa),e=d?d.styleElement:null,f=b.m;b.m=d&&d.m||this.ob(c);var g=b.m;var k=pe;k=e?e.textContent||"":ne(k,a,b.v,g);var m=X(a),p=m.H;p&&!S&&p!==e&&(p._useCount--,0>=p._useCount&&p.parentNode&&p.parentNode.removeChild(p));S?m.H?(m.H.textContent=k,e=m.H):k&&(e=xd(k,g,a.shadowRoot,m.placeholder)):e?e.parentNode||(de&&-1<k.indexOf("@media")&&(e.textContent=k),yd(e,null,m.placeholder)):k&&(e=xd(k,g,null,m.placeholder));e&&(e._useCount=e._useCount||0,m.H!=
e&&e._useCount++,m.H=e);g=e;S||(e=b.m,m=k=a.getAttribute("class")||"",f&&(m=k.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),m+=(m?" ":"")+"x-scope "+e,k!==m&&Gd(a,m));d||Ie.store(c,b.v,g,b.m);return g};l.ka=function(a,b){var c=this.ia(a),d=X(c),e=d.v;c===this.F||e||(this.ka(c,d),e=d.v);c=Object.create(e||null);e=me(a,b.o,b.cssBuild);a=ke(d.o,a).u;Object.assign(c,e.Zb,a,e.fc);this.xb(c,b.J);a=pe;d=Object.getOwnPropertyNames(c);e=0;for(var f;e<d.length;e++)f=d[e],c[f]=ie(a,c[f],c);b.v=c};
l.xb=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};l.styleDocument=function(a){this.styleSubtree(this.F,a)};l.styleSubtree=function(a,b){var c=Hd(a),d=c.shadowRoot,e=this.ga(a);(d||e)&&this.styleElement(a,b);if(a=e?c:d)for(a=Array.from(a.querySelectorAll("*")).filter(function(f){return Hd(f).shadowRoot}),b=0;b<a.length;b++)this.styleSubtree(a[b])};l.Hb=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.Gb(c)}};
l.ab=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&oe(c,this.s.v)}};l.Ta=function(a){var b=this,c=Jd(a);c!==this.s.cssBuild&&(this.s.cssBuild=c);if(!Kd(c)){var d=vd(a);ud(d,function(e){if(S)Zd(e);else{var f=W;e.selector=e.parsedSelector;Zd(e);f.Ha(e,f.Mb)}T&&""===c&&(b.K(),b.g&&b.g.transformRule(e))});T?a.textContent=td(d):this.s.o.rules.push(d)}};l.Gb=function(a){if(T&&this.g){var b=vd(a);this.K();this.g.transformRules(b);a.textContent=td(b)}};
l.getComputedStyleValue=function(a,b){var c;T||(c=(X(a)||X(this.ia(a))).v[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};l.kc=function(a,b){var c=Hd(a).getRootNode();b=b?("string"===typeof b?b:String(b)).split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.R){c=d[e+1];break}}}c&&b.push(W.R,c);T||(c=X(a))&&c.m&&b.push(pe.Wa,c.m);Gd(a,b.join(" "))};l.Kb=function(a){return X(a)};
l.jc=function(a,b){W.element(a,b)};l.nc=function(a,b){W.element(a,b,!0)};l.ic=function(a){return xe(a)};l.Tb=function(a){return we(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.kc;
Y.prototype._styleInfoForNode=Y.prototype.Kb;Y.prototype.transformCustomStyleForDocument=Y.prototype.Ta;Y.prototype.getStyleAst=Y.prototype.Wb;Y.prototype.styleAstToString=Y.prototype.lc;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Y.prototype.scopeNode=Y.prototype.jc;Y.prototype.unscopeNode=Y.prototype.nc;Y.prototype.scopeForNode=Y.prototype.ic;Y.prototype.currentScopeForNode=Y.prototype.Tb;Y.prototype.prepareAdoptedCssText=Y.prototype.dc;
Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return S}},nativeCss:{get:function(){return T}}});var Z=new Y,Ke,Le;window.ShadyCSS&&(Ke=window.ShadyCSS.ApplyShim,Le=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:T,nativeShadow:S,cssBuild:kd,disableRuntime:ld};Ke&&(window.ShadyCSS.ApplyShim=Ke);Le&&(window.ShadyCSS.CustomStyleInterface=Le);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at
 http://polymer.github.io/LICENSE.txt The complete set of authors may be found
 at http://polymer.github.io/AUTHORS.txt The complete set of contributors may
 be found at http://polymer.github.io/CONTRIBUTORS.txt Code distributed by
 Google as part of the polymer project is also subject to an additional IP
 rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Me=document.createElement("style");Me.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Ne=document.querySelector("head");Ne.insertBefore(Me,Ne.firstChild);/*

Copyright (c) 2019 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
})();
//# sourceMappingURL=webcomponents-hi-sd.js.sourcemap
